// AUTO-GENERATED by tools/i18n-cache-buster.mjs — do not edit by hand.
// First 12 hex of sha256(en.json + pl.json). The i18n JSONs ship unhashed
// and long-cached; this version busts the browser cache exactly when the
// translations change. Gate: npm run check:i18n-cache-buster.
export const I18N_VERSION = '35a62a7199b6';
