// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddressDtoIn } from '../model/models';
import { AddressDtoOut } from '../model/models';
import { PageAddressDtoOut } from '../model/models';
import { Pageable } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Create12RequestParams {
    addressDtoIn: AddressDtoIn;
}

export interface CreateAddressForOpportunityRequestParams {
    opportunityId: number;
    addressDtoIn: AddressDtoIn;
}

export interface CreateAddressForUserRequestParams {
    userId: number;
    addressDtoIn: AddressDtoIn;
}

export interface Delete12RequestParams {
    ids: Array<number>;
}

export interface FindPaginated12RequestParams {
    pageable: Pageable;
    filters: { [key: string]: string; };
}

export interface GetAddressesByOpportunityIdRequestParams {
    opportunityId: number;
}

export interface GetAddressesByOpportunityIdAndTypeRequestParams {
    opportunityId: number;
    type: string;
}

export interface GetAddressesByUserIdRequestParams {
    userId: number;
}

export interface GetAddressesByUserIdAndTypeRequestParams {
    userId: number;
    type: string;
}

export interface GetById12RequestParams {
    id: number;
}

export interface GetPrimaryAddressByOpportunityIdRequestParams {
    opportunityId: number;
}

export interface GetPrimaryAddressByUserIdRequestParams {
    userId: number;
}

export interface Patch12RequestParams {
    id: number;
    requestBody: { [key: string]: object; };
}

export interface SearchReusableAddressesRequestParams {
    street?: string;
    city?: string;
    postalCode?: string;
    country?: string;
}

export interface SetAsPrimaryRequestParams {
    id: number;
}

export interface Update12RequestParams {
    id: number;
    addressDtoIn: AddressDtoIn;
}


export interface AddressAPIServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new address
     * Creates a new address based on the provided data
* @param requestParameters
     */
    create12(requestParameters: Create12RequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Create address for opportunity
     * Creates a new address associated with the specified partnership opportunity
* @param requestParameters
     */
    createAddressForOpportunity(requestParameters: CreateAddressForOpportunityRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Create address for user
     * Creates a new address associated with the specified user
* @param requestParameters
     */
    createAddressForUser(requestParameters: CreateAddressForUserRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Delete addresses
     * Deletes one or more addresses if the user has permission
* @param requestParameters
     */
    delete12(requestParameters: Delete12RequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get paginated entities
     * Retrieves a paginated list of entities with optional filtering
* @param requestParameters
     */
    findPaginated12(requestParameters: FindPaginated12RequestParams, extraHttpRequestParams?: any): Observable<PageAddressDtoOut>;

    /**
     * Get all address types
     * Returns a list of all available address types
*/
    getAddressTypes(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Get addresses by opportunity ID
     * Returns all addresses for a specific partnership opportunity
* @param requestParameters
     */
    getAddressesByOpportunityId(requestParameters: GetAddressesByOpportunityIdRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Get opportunity addresses by type
     * Returns all addresses of a specific type for a partnership opportunity
* @param requestParameters
     */
    getAddressesByOpportunityIdAndType(requestParameters: GetAddressesByOpportunityIdAndTypeRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Get addresses by user ID
     * Returns all addresses for a specific user
* @param requestParameters
     */
    getAddressesByUserId(requestParameters: GetAddressesByUserIdRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Get user addresses by type
     * Returns all addresses of a specific type for a user
* @param requestParameters
     */
    getAddressesByUserIdAndType(requestParameters: GetAddressesByUserIdAndTypeRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Get address by ID
     * Returns an address by its ID if the user has permission
* @param requestParameters
     */
    getById12(requestParameters: GetById12RequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Get primary address by opportunity ID
     * Returns the primary address for a specific partnership opportunity
* @param requestParameters
     */
    getPrimaryAddressByOpportunityId(requestParameters: GetPrimaryAddressByOpportunityIdRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Get primary address by user ID
     * Returns the primary address for a specific user
* @param requestParameters
     */
    getPrimaryAddressByUserId(requestParameters: GetPrimaryAddressByUserIdRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Partially update entity
     * Updates specific fields of an existing entity
* @param requestParameters
     */
    patch12(requestParameters: Patch12RequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Search for reusable addresses
     * Finds existing addresses that match the given criteria and can be reused for new opportunities. All parameters are optional and support partial matching (case-insensitive).
* @param requestParameters
     */
    searchReusableAddresses(requestParameters: SearchReusableAddressesRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Set address as primary
     * Sets the specified address as primary, unsetting any existing primary address
* @param requestParameters
     */
    setAsPrimary(requestParameters: SetAsPrimaryRequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

    /**
     * Update an address
     * Updates an existing address if the user has permission
* @param requestParameters
     */
    update12(requestParameters: Update12RequestParams, extraHttpRequestParams?: any): Observable<AddressDtoOut>;

}
