// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiErrorResponse } from '../model/models';
import { Permission } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface SetUserClaimsRequestParams {
    uid: string;
    permission: Array<Permission>;
}


export interface AdminControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    setUserClaims(requestParameters: SetUserClaimsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
