// @ts-nocheck
export * from './active-cooperation-controller.api';
import { ActiveCooperationControllerService } from './active-cooperation-controller.api';
export * from './active-cooperation-controller.apiInterface';
export * from './address-api.api';
import { AddressAPIService } from './address-api.api';
export * from './address-api.apiInterface';
export * from './admin-cascade-delete-controller.api';
import { AdminCascadeDeleteControllerService } from './admin-cascade-delete-controller.api';
export * from './admin-cascade-delete-controller.apiInterface';
export * from './admin-controller.api';
import { AdminControllerService } from './admin-controller.api';
export * from './admin-controller.apiInterface';
export * from './applied-opportunity-content-controller.api';
import { AppliedOpportunityContentControllerService } from './applied-opportunity-content-controller.api';
export * from './applied-opportunity-content-controller.apiInterface';
export * from './applied-opportunity-controller.api';
import { AppliedOpportunityControllerService } from './applied-opportunity-controller.api';
export * from './applied-opportunity-controller.apiInterface';
export * from './auth-controller.api';
import { AuthControllerService } from './auth-controller.api';
export * from './auth-controller.apiInterface';
export * from './city-controller.api';
import { CityControllerService } from './city-controller.api';
export * from './city-controller.apiInterface';
export * from './consent-admin-controller.api';
import { ConsentAdminControllerService } from './consent-admin-controller.api';
export * from './consent-admin-controller.apiInterface';
export * from './consent-controller.api';
import { ConsentControllerService } from './consent-controller.api';
export * from './consent-controller.apiInterface';
export * from './content-type-controller.api';
import { ContentTypeControllerService } from './content-type-controller.api';
export * from './content-type-controller.apiInterface';
export * from './currency-controller.api';
import { CurrencyControllerService } from './currency-controller.api';
export * from './currency-controller.apiInterface';
export * from './custom-error-controller.api';
import { CustomErrorControllerService } from './custom-error-controller.api';
export * from './custom-error-controller.apiInterface';
export * from './dictionary-controller.api';
import { DictionaryControllerService } from './dictionary-controller.api';
export * from './dictionary-controller.apiInterface';
export * from './enum-metadata-controller.api';
import { EnumMetadataControllerService } from './enum-metadata-controller.api';
export * from './enum-metadata-controller.apiInterface';
export * from './faq-category-controller.api';
import { FaqCategoryControllerService } from './faq-category-controller.api';
export * from './faq-category-controller.apiInterface';
export * from './faq-controller.api';
import { FaqControllerService } from './faq-controller.api';
export * from './faq-controller.apiInterface';
export * from './file-management-controller.api';
import { FileManagementControllerService } from './file-management-controller.api';
export * from './file-management-controller.apiInterface';
export * from './file-upload.api';
import { FileUploadService } from './file-upload.api';
export * from './file-upload.apiInterface';
export * from './firebase-auth-proxy-controller.api';
import { FirebaseAuthProxyControllerService } from './firebase-auth-proxy-controller.api';
export * from './firebase-auth-proxy-controller.apiInterface';
export * from './geo-ip-admin.api';
import { GeoIPAdminService } from './geo-ip-admin.api';
export * from './geo-ip-admin.apiInterface';
export * from './geo-location-gdpr-controller.api';
import { GeoLocationGdprControllerService } from './geo-location-gdpr-controller.api';
export * from './geo-location-gdpr-controller.apiInterface';
export * from './health-controller.api';
import { HealthControllerService } from './health-controller.api';
export * from './health-controller.apiInterface';
export * from './instagram-callback-controller.api';
import { InstagramCallbackControllerService } from './instagram-callback-controller.api';
export * from './instagram-callback-controller.apiInterface';
export * from './legal-admin-controller.api';
import { LegalAdminControllerService } from './legal-admin-controller.api';
export * from './legal-admin-controller.apiInterface';
export * from './legal-controller.api';
import { LegalControllerService } from './legal-controller.api';
export * from './legal-controller.apiInterface';
export * from './notifications.api';
import { NotificationsService } from './notifications.api';
export * from './notifications.apiInterface';
export * from './partnership-opportunity-api.api';
import { PartnershipOpportunityAPIService } from './partnership-opportunity-api.api';
export * from './partnership-opportunity-api.apiInterface';
export * from './platform-controller.api';
import { PlatformControllerService } from './platform-controller.api';
export * from './platform-controller.apiInterface';
export * from './public-config-controller.api';
import { PublicConfigControllerService } from './public-config-controller.api';
export * from './public-config-controller.apiInterface';
export * from './rate-limit-privacy-controller.api';
import { RateLimitPrivacyControllerService } from './rate-limit-privacy-controller.api';
export * from './rate-limit-privacy-controller.apiInterface';
export * from './registry.api';
import { RegistryService } from './registry.api';
export * from './registry.apiInterface';
export * from './service-type-controller.api';
import { ServiceTypeControllerService } from './service-type-controller.api';
export * from './service-type-controller.apiInterface';
export * from './step-up-auth-controller.api';
import { StepUpAuthControllerService } from './step-up-auth-controller.api';
export * from './step-up-auth-controller.apiInterface';
export * from './support-ticket-controller.api';
import { SupportTicketControllerService } from './support-ticket-controller.api';
export * from './support-ticket-controller.apiInterface';
export * from './two-factor-status-controller.api';
import { TwoFactorStatusControllerService } from './two-factor-status-controller.api';
export * from './two-factor-status-controller.apiInterface';
export * from './upload-administration.api';
import { UploadAdministrationService } from './upload-administration.api';
export * from './upload-administration.apiInterface';
export * from './user-controller.api';
import { UserControllerService } from './user-controller.api';
export * from './user-controller.apiInterface';
export * from './user-preferences-controller.api';
import { UserPreferencesControllerService } from './user-preferences-controller.api';
export * from './user-preferences-controller.apiInterface';
export * from './user-social-connection-controller.api';
import { UserSocialConnectionControllerService } from './user-social-connection-controller.api';
export * from './user-social-connection-controller.apiInterface';
export * from './webhook-controller.api';
import { WebhookControllerService } from './webhook-controller.api';
export * from './webhook-controller.apiInterface';
export const APIS = [ActiveCooperationControllerService, AddressAPIService, AdminCascadeDeleteControllerService, AdminControllerService, AppliedOpportunityContentControllerService, AppliedOpportunityControllerService, AuthControllerService, CityControllerService, ConsentAdminControllerService, ConsentControllerService, ContentTypeControllerService, CurrencyControllerService, CustomErrorControllerService, DictionaryControllerService, EnumMetadataControllerService, FaqCategoryControllerService, FaqControllerService, FileManagementControllerService, FileUploadService, FirebaseAuthProxyControllerService, GeoIPAdminService, GeoLocationGdprControllerService, HealthControllerService, InstagramCallbackControllerService, LegalAdminControllerService, LegalControllerService, NotificationsService, PartnershipOpportunityAPIService, PlatformControllerService, PublicConfigControllerService, RateLimitPrivacyControllerService, RegistryService, ServiceTypeControllerService, StepUpAuthControllerService, SupportTicketControllerService, TwoFactorStatusControllerService, UploadAdministrationService, UserControllerService, UserPreferencesControllerService, UserSocialConnectionControllerService, WebhookControllerService];
