// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiErrorResponse } from '../model/models';
import { AppliedOpportunityContentDtoIn } from '../model/models';
import { AppliedOpportunityContentDtoOut } from '../model/models';
import { ContentApprovalStatus } from '../model/models';
import { PageAppliedOpportunityContentDtoOut } from '../model/models';
import { Pageable } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApproveContentRequestParams {
    contentId: number;
    approvalNotes?: string;
}

export interface DeleteContentRequestParams {
    contentId: number;
}

export interface GetContentRequestParams {
    contentId: number;
}

export interface GetContentByAppliedOpportunityRequestParams {
    appliedOpportunityId: number;
    contentStatus?: ContentApprovalStatus;
}

export interface GetContentByAppliedOpportunityPagedRequestParams {
    appliedOpportunityId: number;
    pageable: Pageable;
    filters: { [key: string]: string; };
}

export interface GetContentByStatusRequestParams {
    status: ContentApprovalStatus;
}

export interface RejectContentRequestParams {
    contentId: number;
    approvalNotes?: string;
}

export interface SubmitContentRequestParams {
    appliedOpportunityContentDtoIn: AppliedOpportunityContentDtoIn;
}

export interface UpdateContentRequestParams {
    contentId: number;
    appliedOpportunityContentDtoIn: AppliedOpportunityContentDtoIn;
}

export interface UpdateEngagementMetricsRequestParams {
    contentId: number;
    likes?: number;
    comments?: number;
    views?: number;
    shares?: number;
}


export interface AppliedOpportunityContentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Approve content
     * Approve content submission (admin/company only)
* @param requestParameters
     */
    approveContent(requestParameters: ApproveContentRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete content
     * Delete content submission (content owner or admin only)
* @param requestParameters
     */
    deleteContent(requestParameters: DeleteContentRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get content by ID
     * Retrieve specific content submission
* @param requestParameters
     */
    getContent(requestParameters: GetContentRequestParams, extraHttpRequestParams?: any): Observable<AppliedOpportunityContentDtoOut>;

    /**
     * Get content by applied opportunity
     * Retrieves content for specific applied opportunity with optional status filtering
* @param requestParameters
     */
    getContentByAppliedOpportunity(requestParameters: GetContentByAppliedOpportunityRequestParams, extraHttpRequestParams?: any): Observable<Array<AppliedOpportunityContentDtoOut>>;

    /**
     * Get paginated content by applied opportunity
     * Retrieves paginated content for specific applied opportunity with optional filtering
* @param requestParameters
     */
    getContentByAppliedOpportunityPaged(requestParameters: GetContentByAppliedOpportunityPagedRequestParams, extraHttpRequestParams?: any): Observable<PageAppliedOpportunityContentDtoOut>;

    /**
     * Get content by status
     * Retrieve content by approval status (admin only)
* @param requestParameters
     */
    getContentByStatus(requestParameters: GetContentByStatusRequestParams, extraHttpRequestParams?: any): Observable<Array<AppliedOpportunityContentDtoOut>>;

    /**
     * Get pending content
     * Retrieve all content pending approval (admin/company only)
*/
    getPendingContent(extraHttpRequestParams?: any): Observable<Array<AppliedOpportunityContentDtoOut>>;

    /**
     * Reject content
     * Reject content submission (admin/company only)
* @param requestParameters
     */
    rejectContent(requestParameters: RejectContentRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Submit new content
     * Submit content for an applied opportunity (influencer only)
* @param requestParameters
     */
    submitContent(requestParameters: SubmitContentRequestParams, extraHttpRequestParams?: any): Observable<AppliedOpportunityContentDtoOut>;

    /**
     * Update content submission
     * Update existing content submission (content owner only)
* @param requestParameters
     */
    updateContent(requestParameters: UpdateContentRequestParams, extraHttpRequestParams?: any): Observable<AppliedOpportunityContentDtoOut>;

    /**
     * Update engagement metrics
     * Update engagement metrics for content (content owner only)
* @param requestParameters
     */
    updateEngagementMetrics(requestParameters: UpdateEngagementMetricsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
