// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UserConsentDtoIn } from '../model/models';
import { UserConsentDtoOut } from '../model/models';
import { UserCurrentConsentDtoOut } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetMyConsentHistoryRequestParams {
    consentType: string;
}

export interface RecordMyConsentRequestParams {
    userConsentDtoIn: UserConsentDtoIn;
}


export interface ConsentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    getMyConsentHistory(requestParameters: GetMyConsentHistoryRequestParams, extraHttpRequestParams?: any): Observable<Array<UserConsentDtoOut>>;

    /**
     * 
     * 
*/
    getMyConsents(extraHttpRequestParams?: any): Observable<Array<UserCurrentConsentDtoOut>>;

    /**
     * 
     * 
* @param requestParameters
     */
    recordMyConsent(requestParameters: RecordMyConsentRequestParams, extraHttpRequestParams?: any): Observable<UserConsentDtoOut>;

}
