// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CurrencyDto } from '../model/models';
import { CurrencyDtoOut } from '../model/models';
import { PageCurrencyDtoOut } from '../model/models';
import { Pageable } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Create8RequestParams {
    currencyDto: CurrencyDto;
}

export interface Delete8RequestParams {
    ids: Array<number>;
}

export interface FindPaginated8RequestParams {
    pageable: Pageable;
    filters: { [key: string]: string; };
}

export interface GetById8RequestParams {
    id: number;
}

export interface Patch8RequestParams {
    id: number;
    requestBody: { [key: string]: object; };
}

export interface Update8RequestParams {
    id: number;
    currencyDto: CurrencyDto;
}


export interface CurrencyControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new entity
     * Creates a new entity with the provided data
* @param requestParameters
     */
    create8(requestParameters: Create8RequestParams, extraHttpRequestParams?: any): Observable<CurrencyDtoOut>;

    /**
     * Delete entities
     * Deletes one or more entities if the user has permission
* @param requestParameters
     */
    delete8(requestParameters: Delete8RequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get paginated entities
     * Retrieves a paginated list of entities with optional filtering
* @param requestParameters
     */
    findPaginated8(requestParameters: FindPaginated8RequestParams, extraHttpRequestParams?: any): Observable<PageCurrencyDtoOut>;

    /**
     * Get entity by ID
     * Retrieves an entity by its unique identifier
* @param requestParameters
     */
    getById8(requestParameters: GetById8RequestParams, extraHttpRequestParams?: any): Observable<CurrencyDtoOut>;

    /**
     * Partially update entity
     * Updates specific fields of an existing entity
* @param requestParameters
     */
    patch8(requestParameters: Patch8RequestParams, extraHttpRequestParams?: any): Observable<CurrencyDtoOut>;

    /**
     * Update entity
     * Updates an existing entity with the provided data
* @param requestParameters
     */
    update8(requestParameters: Update8RequestParams, extraHttpRequestParams?: any): Observable<CurrencyDtoOut>;

}
