// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GeoLocation } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface LookupIpRequestParams {
    ip: string;
}

export interface TestImpossibleTravelRequestParams {
    fromIp: string;
    toIp: string;
    minutes: number;
}


export interface GeoIPAdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Clean expired cache
     * Force cleanup of expired GeoIP cache entries
*/
    cleanCache(extraHttpRequestParams?: any): Observable<{ [key: string]: string; }>;

    /**
     * Get GeoIP metrics
     * Returns cache hit rates and service statistics
*/
    getMetrics(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * Get my location
     * Returns geolocation for the current request IP
*/
    getMyLocation(extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * Lookup IP location
     * Get geolocation data for a specific IP address
* @param requestParameters
     */
    lookupIp(requestParameters: LookupIpRequestParams, extraHttpRequestParams?: any): Observable<GeoLocation>;

    /**
     * Test impossible travel with full analysis
     * Test travel detection between two IPs with risk scoring and detailed analysis
* @param requestParameters
     */
    testImpossibleTravel(requestParameters: TestImpossibleTravelRequestParams, extraHttpRequestParams?: any): Observable<{ [key: string]: object; }>;

    /**
     * Update GeoIP database
     * Force immediate update of MaxMind GeoLite2 database
*/
    updateDatabase(extraHttpRequestParams?: any): Observable<{ [key: string]: string; }>;

}
