// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiErrorResponse } from '../model/models';
import { ConsentRecordAdminDtoOut } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetConsentRecordsRequestParams {
    userId: number;
}

export interface GetOrphanedAnonymousRequestParams {
    hoursBack?: number;
}


export interface LegalAdminControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    getConsentRecords(requestParameters: GetConsentRecordsRequestParams, extraHttpRequestParams?: any): Observable<Array<ConsentRecordAdminDtoOut>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getOrphanedAnonymous(requestParameters: GetOrphanedAnonymousRequestParams, extraHttpRequestParams?: any): Observable<Array<ConsentRecordAdminDtoOut>>;

}
