// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiErrorResponse } from '../model/models';
import { MarkAllReadResponse } from '../model/models';
import { NotificationDtoOut } from '../model/models';
import { PageNotificationDtoOut } from '../model/models';
import { UnreadCountDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ArchiveNotificationRequestParams {
    id: number;
}

export interface GetByGroupKeyRequestParams {
    groupKey: string;
}

export interface GetNotificationRequestParams {
    id: number;
}

export interface GetNotificationsRequestParams {
    page?: number;
    size?: number;
}

export interface MarkAsReadRequestParams {
    id: number;
}


export interface NotificationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Archive notification
     * Archives a notification (soft delete). Archived notifications are hidden from the main list but preserved in database.
* @param requestParameters
     */
    archiveNotification(requestParameters: ArchiveNotificationRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get notifications by group
     * Returns all notifications for a specific workflow group (e.g., collaboration). Useful for showing notification history on detail pages.
* @param requestParameters
     */
    getByGroupKey(requestParameters: GetByGroupKeyRequestParams, extraHttpRequestParams?: any): Observable<Array<NotificationDtoOut>>;

    /**
     * Get notification by ID
     * Returns a single notification. User can only access their own notifications.
* @param requestParameters
     */
    getNotification(requestParameters: GetNotificationRequestParams, extraHttpRequestParams?: any): Observable<NotificationDtoOut>;

    /**
     * Get user notifications
     * Returns paginated notifications for the current user, excluding archived. Sorted by creation date descending (newest first).
* @param requestParameters
     */
    getNotifications(requestParameters: GetNotificationsRequestParams, extraHttpRequestParams?: any): Observable<PageNotificationDtoOut>;

    /**
     * Get unread notification count
     * Returns the count of unread, non-archived notifications. Used for displaying the badge on the notification bell icon.
*/
    getUnreadCount(extraHttpRequestParams?: any): Observable<UnreadCountDto>;

    /**
     * Mark all notifications as read
     * Marks all unread, non-archived notifications as read for the current user.
*/
    markAllAsRead(extraHttpRequestParams?: any): Observable<MarkAllReadResponse>;

    /**
     * Mark notification as read
     * Marks a single notification as read. Returns the updated notification.
* @param requestParameters
     */
    markAsRead(requestParameters: MarkAsReadRequestParams, extraHttpRequestParams?: any): Observable<NotificationDtoOut>;

}
