// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageServiceTypeDtoOut } from '../model/models';
import { Pageable } from '../model/models';
import { ServiceTypeDto } from '../model/models';
import { ServiceTypeDtoOut } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Create5RequestParams {
    serviceTypeDto: ServiceTypeDto;
}

export interface Delete5RequestParams {
    ids: Array<number>;
}

export interface FindPaginated5RequestParams {
    pageable: Pageable;
    filters: { [key: string]: string; };
}

export interface GetById5RequestParams {
    id: number;
}

export interface Patch5RequestParams {
    id: number;
    requestBody: { [key: string]: object; };
}

export interface Update5RequestParams {
    id: number;
    serviceTypeDto: ServiceTypeDto;
}


export interface ServiceTypeControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new entity
     * Creates a new entity with the provided data
* @param requestParameters
     */
    create5(requestParameters: Create5RequestParams, extraHttpRequestParams?: any): Observable<ServiceTypeDtoOut>;

    /**
     * Delete entities
     * Deletes one or more entities if the user has permission
* @param requestParameters
     */
    delete5(requestParameters: Delete5RequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get paginated entities
     * Retrieves a paginated list of entities with optional filtering
* @param requestParameters
     */
    findPaginated5(requestParameters: FindPaginated5RequestParams, extraHttpRequestParams?: any): Observable<PageServiceTypeDtoOut>;

    /**
     * Get entity by ID
     * Retrieves an entity by its unique identifier
* @param requestParameters
     */
    getById5(requestParameters: GetById5RequestParams, extraHttpRequestParams?: any): Observable<ServiceTypeDtoOut>;

    /**
     * Partially update entity
     * Updates specific fields of an existing entity
* @param requestParameters
     */
    patch5(requestParameters: Patch5RequestParams, extraHttpRequestParams?: any): Observable<ServiceTypeDtoOut>;

    /**
     * Update entity
     * Updates an existing entity with the provided data
* @param requestParameters
     */
    update5(requestParameters: Update5RequestParams, extraHttpRequestParams?: any): Observable<ServiceTypeDtoOut>;

}
