// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiErrorResponse } from '../model/models';
import { CleanupOutcome } from '../model/models';
import { SystemStats } from '../model/models';
import { UploadStatus } from '../model/models';
import { UploadsByStatus } from '../model/models';
import { UserUploads } from '../model/models';
import { WeeklyReport } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetUploadsByStatusRequestParams {
    status: UploadStatus;
    page?: number;
    size?: number;
}

export interface GetUserUploadsRequestParams {
    userId: string;
    page?: number;
    size?: number;
}


export interface UploadAdministrationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Clean up orphaned uploads
     * Manually trigger cleanup of old pending uploads
*/
    cleanupOrphanedUploads(extraHttpRequestParams?: any): Observable<CleanupOutcome>;

    /**
     * Generate weekly report
     * Creates a weekly summary of upload activity
*/
    generateWeeklyReport(extraHttpRequestParams?: any): Observable<WeeklyReport>;

    /**
     * Get system upload statistics
     * Returns overall system upload metrics and health
*/
    getSystemStats(extraHttpRequestParams?: any): Observable<SystemStats>;

    /**
     * Get uploads by status
     * Returns all uploads with the specified status
* @param requestParameters
     */
    getUploadsByStatus(requestParameters: GetUploadsByStatusRequestParams, extraHttpRequestParams?: any): Observable<UploadsByStatus>;

    /**
     * Get user uploads
     * Returns all uploads for a specific user
* @param requestParameters
     */
    getUserUploads(requestParameters: GetUserUploadsRequestParams, extraHttpRequestParams?: any): Observable<UserUploads>;

}
