// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageUserPreferencesDtoOut } from '../model/models';
import { Pageable } from '../model/models';
import { UserPreferencesDtoIn } from '../model/models';
import { UserPreferencesDtoOut } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Create2RequestParams {
    userPreferencesDtoIn: UserPreferencesDtoIn;
}

export interface Delete2RequestParams {
    ids: Array<number>;
}

export interface FindPaginated2RequestParams {
    pageable: Pageable;
    filters: { [key: string]: string; };
}

export interface GetById2RequestParams {
    id: number;
}

export interface GetUserPreferencesRequestParams {
    userId: number;
}

export interface Patch2RequestParams {
    id: number;
    requestBody: { [key: string]: object; };
}

export interface PatchCurrentUserPreferencesRequestParams {
    requestBody: { [key: string]: object; };
}

export interface PatchUserPreferencesRequestParams {
    userId: number;
    requestBody: { [key: string]: object; };
}

export interface Update2RequestParams {
    id: number;
    userPreferencesDtoIn: UserPreferencesDtoIn;
}

export interface UpdateCurrentUserPreferencesRequestParams {
    userPreferencesDtoIn: UserPreferencesDtoIn;
}


export interface UserPreferencesControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new entity
     * Creates a new entity with the provided data
* @param requestParameters
     */
    create2(requestParameters: Create2RequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * Delete entities
     * Deletes one or more entities if the user has permission
* @param requestParameters
     */
    delete2(requestParameters: Delete2RequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get paginated entities
     * Retrieves a paginated list of entities with optional filtering
* @param requestParameters
     */
    findPaginated2(requestParameters: FindPaginated2RequestParams, extraHttpRequestParams?: any): Observable<PageUserPreferencesDtoOut>;

    /**
     * Get entity by ID
     * Retrieves an entity by its unique identifier
* @param requestParameters
     */
    getById2(requestParameters: GetById2RequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * 
     * 
*/
    getCurrentUserPreferences(extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * 
     * 
* @param requestParameters
     */
    getUserPreferences(requestParameters: GetUserPreferencesRequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * Partially update entity
     * Updates specific fields of an existing entity
* @param requestParameters
     */
    patch2(requestParameters: Patch2RequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * 
     * 
* @param requestParameters
     */
    patchCurrentUserPreferences(requestParameters: PatchCurrentUserPreferencesRequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * 
     * 
* @param requestParameters
     */
    patchUserPreferences(requestParameters: PatchUserPreferencesRequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * Update entity
     * Updates an existing entity with the provided data
* @param requestParameters
     */
    update2(requestParameters: Update2RequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateCurrentUserPreferences(requestParameters: UpdateCurrentUserPreferencesRequestParams, extraHttpRequestParams?: any): Observable<UserPreferencesDtoOut>;

}
