// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum AddressSourceType {
    COPIED_FROM_USER = 'COPIED_FROM_USER',
    BUSINESS_LOCATION = 'BUSINESS_LOCATION',
    CUSTOM = 'CUSTOM'
}

