// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfluencerPublicProfileDto } from './influencer-public-profile-dto';
import { RateStatusDtoOut } from './rate-status-dto-out';
import { OpportunityStatusDtoOut } from './opportunity-status-dto-out';
import { AppliedOpportunityContentSimpleDtoOut } from './applied-opportunity-content-simple-dto-out';


export interface AppliedOpportunitySimpleDtoOut { 
    companyRateStatus?: RateStatusDtoOut;
    contentSubmissions?: Array<AppliedOpportunityContentSimpleDtoOut>;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    createdTime?: string;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    executionDate?: string;
    id?: number;
    influencer?: InfluencerPublicProfileDto;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    lastUpdateTime?: string;
    note?: string;
    opportunityStatus?: OpportunityStatusDtoOut;
    rateStatus?: RateStatusDtoOut;
    updater?: string;
}

