// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpportunityStatus } from './opportunity-status';
import { RateStatus } from './rate-status';


export interface AppliedOpportunityDtoIn { 
    companyRateStatus?: RateStatus;
    executionDate?: string;
    influencer?: number;
    note?: string;
    opportunityStatus?: OpportunityStatus;
    partnershipOpportunity: number;
    rateStatus?: RateStatus;
    version?: number;
}



