// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpportunityStatus } from './opportunity-status';


export interface AppliedOpportunityStatusHistoryDtoOut { 
    appliedOpportunityId?: number;
    changeReason?: string;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    changedAt?: string;
    changedByFirebaseId?: string;
    changedByUserId?: number;
    changedByUserName?: string;
    id?: number;
    newStatus?: OpportunityStatus;
    notes?: string;
    previousStatus?: OpportunityStatus;
}



