// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BatchCascadeDeleteRequest { 
    expectedTotalEntityCount: number;
    reason?: string;
    /**
     * List of user IDs to cascade-delete. Maximum 10 per batch to prevent accidental mass deletion.
     */
    userIds?: Array<number>;
}

