// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityTypeCount } from './entity-type-count';


export interface CascadeDeletePreview { 
    confirmationCode?: string;
    entityBreakdown?: Array<EntityTypeCount>;
    existsInFirebaseAuth?: boolean;
    firebaseUserId?: string;
    hasFirebaseStorageData?: boolean;
    hasFirestoreInstagramData?: boolean;
    hasFirestoreTotpData?: boolean;
    systemsToClean?: Array<string>;
    totalEntityCount?: number;
    userEmail?: string;
    userId?: number;
    userName?: string;
    userType?: string;
    warnings?: Array<string>;
}

