// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatusDtoOut } from './account-status-dto-out';
import { AddressNoUserDtoOut } from './address-no-user-dto-out';


export interface CompanyPublicProfileDto { 
    accountStatus?: AccountStatusDtoOut;
    addresses?: Array<AddressNoUserDtoOut>;
    description?: string;
    email?: string;
    id?: number;
    name?: string;
    phoneNumber?: string;
    premium?: boolean;
    profilePicture?: string;
    website?: string;
}

