// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentProofDtoIn } from './consent-proof-dto-in';


export interface ConsentPrepareRequest { 
    documentHash?: string;
    /**
     * LegalDocumentType enum name
     */
    documentType?: ConsentPrepareRequestDocumentTypeEnum;
    proof: ConsentProofDtoIn;
    version: number;
}
export enum ConsentPrepareRequestDocumentTypeEnum {
    COOKIE_POLICY = 'COOKIE_POLICY',
    TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
    PRIVACY_POLICY = 'PRIVACY_POLICY',
    SUBSCRIPTION_ACTIVATION_CONSENT = 'SUBSCRIPTION_ACTIVATION_CONSENT',
    DATA_RETENTION_POLICY = 'DATA_RETENTION_POLICY'
};



