// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FaqCategoryDtoIn { 
    active?: boolean;
    description?: string;
    displayOrder?: number;
    name?: string;
}

