// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FaqDtoIn { 
    active?: boolean;
    answer?: string;
    categoryId?: number;
    displayOrder?: number;
    question?: string;
}

