// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FaqDtoOut } from './faq-dto-out';


export interface FaqCategoryDtoOut { 
    active?: boolean;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    createdTime?: string;
    description?: string;
    displayOrder?: number;
    faqs?: Array<FaqDtoOut>;
    id?: number;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    lastUpdateTime?: string;
    name?: string;
    updaterId?: string;
}

