// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileOperationResponse { 
    correlationId?: string;
    data?: { [key: string]: object; };
    error?: string;
    message?: string;
    success?: boolean;
    timestamp?: number;
}

