// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeoLocation { 
    city?: string;
    country?: string;
    countryCode?: string;
    ip?: string;
    isProxy?: boolean;
    isTor?: boolean;
    isVpn?: boolean;
    ispName?: string;
    known?: boolean;
    latitude?: number;
    longitude?: number;
    postalCode?: string;
    region?: string;
    timezone?: string;
}

