// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatusDtoOut } from './account-status-dto-out';


export interface InfluencerPublicProfileDto { 
    accountStatus?: AccountStatusDtoOut;
    createdTime?: string;
    displayName?: string;
    followersCount?: number;
    id?: number;
    name?: string;
    platformName?: string;
    premium?: boolean;
    profilePicture?: string;
    profileUrl?: string;
}

