// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatusDtoOut } from './account-status-dto-out';


export interface InfluencerPublicProfileDto { 
    accountStatus?: AccountStatusDtoOut;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    createdTime?: string;
    displayName?: string;
    followersCount?: number;
    id?: number;
    name?: string;
    platformName?: string;
    premium?: boolean;
    profilePicture?: string;
    profileUrl?: string;
}

