// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyType } from './company-type';


export interface NipLookupResponse { 
    apartmentNumber?: string;
    bankAccounts?: Array<string>;
    buildingNumber?: string;
    city?: string;
    companyActive?: boolean;
    companyName?: string;
    companySuspended?: boolean;
    companyType?: CompanyType;
    krs?: string;
    legalFormName?: string;
    nip?: string;
    ownerName?: string;
    pkdCodes?: Array<{ [key: string]: object; }>;
    pkdMainCode?: string;
    pkdMainDescription?: string;
    postalCode?: string;
    regon?: string;
    sourceCeidg?: boolean;
    sourceGus?: boolean;
    sourceVat?: boolean;
    street?: string;
    vatStatus?: string;
    voivodeship?: string;
}



