// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationSnapshot } from './notification-snapshot';
import { NotificationType } from './notification-type';


export interface NotificationDtoOut { 
    actionLabel?: string;
    actionUrl?: string;
    appliedOpportunityId?: number;
    /**
     * NotificationCategory enum name
     */
    category?: NotificationDtoOutCategoryEnum;
    colorTheme?: string;
    createdAt?: string;
    groupKey?: string;
    icon?: string;
    id?: number;
    isRead?: boolean;
    message?: string;
    /**
     * NotificationPriority enum name
     */
    priority?: NotificationDtoOutPriorityEnum;
    readAt?: string;
    snapshot?: NotificationSnapshot;
    title?: string;
    type?: NotificationType;
}
export enum NotificationDtoOutCategoryEnum {
    PARTNERSHIP = 'PARTNERSHIP',
    ACCOUNT = 'ACCOUNT',
    SUPPORT = 'SUPPORT',
    SYSTEM = 'SYSTEM'
};
export enum NotificationDtoOutPriorityEnum {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
    CRITICAL = 'CRITICAL'
};



