// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpportunityStatus } from './opportunity-status';


export interface OpportunityStatusDtoOut { 
    aliases?: Array<string>;
    colorTheme?: string;
    description?: string;
    icon?: string;
    label?: string;
    originalLabel?: string;
    possibleTransitions?: Array<OpportunityStatus>;
    successful?: boolean;
    terminal?: boolean;
    /**
     * OpportunityStatus enum name
     */
    value?: OpportunityStatus;
}



