// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppliedOpportunityDtoOutInfluencer } from './applied-opportunity-dto-out-influencer';
import { PageableObject } from './pageable-object';
import { SortObject } from './sort-object';


export interface PagePublicProfileDto { 
    content?: Array<AppliedOpportunityDtoOutInfluencer>;
    empty?: boolean;
    first?: boolean;
    last?: boolean;
    number?: number;
    numberOfElements?: number;
    pageable?: PageableObject;
    size?: number;
    sort?: SortObject;
    totalElements?: number;
    totalPages?: number;
}

