// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RateStatusDtoOut { 
    colorTheme?: string;
    icon?: string;
    label?: string;
    originalLabel?: string;
    /**
     * RateStatus enum name
     */
    value?: RateStatusDtoOutValueEnum;
}
export enum RateStatusDtoOutValueEnum {
    DEFAULT = 'DEFAULT',
    POSITIVE = 'POSITIVE',
    NEGATIVE = 'NEGATIVE'
};



