// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseAttachmentDtoOut { 
    contentType?: string;
    downloadUrl?: string;
    fileName?: string;
    fileSize?: number;
    id?: number;
    responseId?: number;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    uploadTime?: string;
}

