// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemStatus } from './system-status';


export interface SystemStatuses { 
    firebaseAuth?: SystemStatus;
    firebaseStorage?: SystemStatus;
    firestoreInstagram?: SystemStatus;
    firestoreTotp?: SystemStatus;
    fullyCompleted?: boolean;
    postgresql?: SystemStatus;
}



