// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What this user has uploaded
 */
export interface UploadHistory { 
    filesUploadedThisHour?: number;
    filesUploadedToday?: number;
    totalFiles?: number;
    totalSizeBytes?: number;
}

