// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatusDtoOut } from './account-status-dto-out';
import { AddressNoUserDtoOut } from './address-no-user-dto-out';
import { UserSocialConnectionDtoOut } from './user-social-connection-dto-out';
import { UserTypeDtoOut } from './user-type-dto-out';


export interface UserDtoOut { 
    accountStatus?: AccountStatusDtoOut;
    addresses?: Array<AddressNoUserDtoOut>;
    companyDescription?: string;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    createdTime?: string;
    daysToAcceptNewTerms?: number;
    email?: string;
    emailVerified?: boolean;
    firebaseUserId?: string;
    firstName?: string;
    id?: number;
    initialAccountSetupCompleted?: boolean;
    lastName?: string;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    lastUpdateTime?: string;
    lastVerifiedEmail?: string;
    name?: string;
    newestConsentsAccepted?: boolean;
    nip?: string;
    noteFromAdmin?: string;
    phoneNumber?: string;
    premium?: boolean;
    profileComplete?: boolean;
    profileMissingFields?: Array<string>;
    profilePicture?: string;
    socialConnections?: Array<UserSocialConnectionDtoOut>;
    updater?: string;
    userType?: UserTypeDtoOut;
}

