// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnectionStatus } from './connection-status';


export interface UserSocialConnectionDtoIn { 
    connectionStatus?: ConnectionStatus;
    displayName?: string;
    email?: string;
    followersCount?: number;
    id?: number;
    isPrimary?: boolean;
    note?: string;
    platform?: number;
    profilePictureUrl?: string;
    profileUrl?: string;
    serviceType?: number;
    socialUserId?: string;
    userId?: number;
}



