// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPreferencesDtoOut { 
    /**
     * EmailFrequency enum name
     */
    communicationFrequency?: UserPreferencesDtoOutCommunicationFrequencyEnum;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    createdTime?: string;
    darkModeEnabled?: boolean;
    gdprMarketingConsent?: boolean;
    id?: number;
    /**
     * UI language code
     */
    language?: UserPreferencesDtoOutLanguageEnum;
    /**
     * Local date and time, ISO-8601, with no UTC offset. Not an RFC 3339 date-time: this value names no time zone.
     */
    lastUpdateTime?: string;
    notificationEmailEnabled?: boolean;
    notificationEmailPartnershipEnabled?: boolean;
    notificationEmailSupportEnabled?: boolean;
    notificationPartnershipEnabled?: boolean;
    notificationPushEnabled?: boolean;
    notificationSmsEnabled?: boolean;
    notificationSupportEnabled?: boolean;
    notificationSystemEnabled?: boolean;
    sharePhoneForPayments?: boolean;
    timezone?: string;
    twoFactorAuthenticationEnabled?: boolean;
    updaterId?: string;
    userId?: number;
}
export enum UserPreferencesDtoOutCommunicationFrequencyEnum {
    IMMEDIATE = 'IMMEDIATE',
    HOURLY_DIGEST = 'HOURLY_DIGEST',
    DAILY_DIGEST = 'DAILY_DIGEST',
    WEEKLY_DIGEST = 'WEEKLY_DIGEST'
};
export enum UserPreferencesDtoOutLanguageEnum {
    PL = 'pl',
    EN = 'en'
};



