// @ts-nocheck
/**
 * CheckItOut Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A code accepted at sign-in
 */
export interface Verified { 
    canAccessAdmin?: boolean;
    message?: string;
    /**
     * The original ID token is still the one to use; no new token is issued
     */
    reuseIdToken?: boolean;
    success?: boolean;
    twoFactorVerified?: boolean;
    verified?: boolean;
}

