// GENERATED by tools/gen-graph-topology.mjs from the Neo4j dump of CheckItOutSystem
// (146 nodes, 167 relationships; descriptions cut at 190 chars). Do not edit.

export type GraphCat = 'app' | 'infra' | 'quality';
export type GraphRole =
  | 'controller'
  | 'configuration'
  | 'security'
  | 'implementation'
  | 'diagnostics'
  | 'lifecycle';

export interface GraphMaster {
  readonly name: string;
  readonly angle: string;
  readonly rebuilt: string;
  readonly ai_description: string;
}
export interface GraphDomain {
  readonly key: string;
  readonly name: string;
  readonly cat: GraphCat;
  readonly ai_description: string;
}
export interface GraphLeaf {
  readonly id: string;
  readonly name: string;
  readonly domain: string;
  readonly role?: GraphRole;
  readonly status: string;
  readonly path: string;
  readonly ai_description: string;
  readonly why?: string;
}
export interface GraphEdge {
  readonly from: string;
  readonly to: string;
  readonly type: string;
  readonly ai_context: string;
}
export interface GraphData {
  readonly master: GraphMaster;
  readonly domains: readonly GraphDomain[];
  readonly leaves: readonly GraphLeaf[];
  readonly edges: readonly GraphEdge[];
}

// prettier-ignore
export const GRAPH_DATA: GraphData = {
 "master": {
  "name": "checkItOut Platform",
  "angle": "startup-in-a-box",
  "rebuilt": "2026-06-06",
  "ai_description": "Unified platform model: app + infrastructure as co-equal sellable assets (startup-in-a-box). Built from verified code via find/grep/read."
 },
 "domains": [
  {
   "key": "app-core",
   "name": "App Core",
   "cat": "app",
   "ai_description": "collaborations, partnership opportunities, users, company"
  },
  {
   "key": "auth-identity",
   "name": "Auth & Identity",
   "cat": "app",
   "ai_description": "TOTP/email step-up, OAuth, session binding, Firebase oobCode, token-version invalidation"
  },
  {
   "key": "billing",
   "name": "Billing Saga",
   "cat": "app",
   "ai_description": "Stripe to Fakturownia (to KSeF) after-commit saga, triple idempotency, dead-letter retry"
  },
  {
   "key": "frontend-v2",
   "name": "Frontend v2 (OSS)",
   "cat": "app",
   "ai_description": "fe-greenfield OpenAPI-typed client, visual parity, MIT"
  },
  {
   "key": "legal-consent",
   "name": "Legal/Consent/RODO",
   "cat": "app",
   "ai_description": "HMAC consent cookies, versioning+grace, RODO audit, cascade-delete via tickets"
  },
  {
   "key": "subscription",
   "name": "Subscription Machine",
   "cat": "app",
   "ai_description": "9-state event-sourced lifecycle, @Version locking, audit trail, terms-grace"
  },
  {
   "key": "backups-dr",
   "name": "Backups & DR",
   "cat": "infra",
   "ai_description": "immutable backup chain, GCS versioned bucket, OVH snapshot, Postgres PITR, Firestore+KMS"
  },
  {
   "key": "geo-security",
   "name": "Geo Security",
   "cat": "infra",
   "ai_description": "MaxMind GeoLite2, 3-tier impossible-travel, Haversine risk, fail-closed-for-admin, GDPR geo handling"
  },
  {
   "key": "hardening",
   "name": "Linux Hardening",
   "cat": "infra",
   "ai_description": "sudoers least-privilege, YubiKey touch SSH, sshd/kernel hardening, fail2ban, apparmor, audit, chattr immutability"
  },
  {
   "key": "network-perimeter",
   "name": "Network Perimeter",
   "cat": "infra",
   "ai_description": "Cloudflare edge real-IP, nginx, iptables, multilayer rate-limit, daily IP-allowlist refresh, mTLS-gated Loki vhost"
  },
  {
   "key": "observability",
   "name": "Observability",
   "cat": "infra",
   "ai_description": "journald to Grafana Alloy to Loki to GCS, mTLS ingress, pentest-activity alert"
  },
  {
   "key": "provisioning",
   "name": "Provisioning (Ansible)",
   "cat": "infra",
   "ai_description": "16 roles bare-Ubuntu to hardened-prod, hardening-last, sudoers allowlist + visudo gate"
  },
  {
   "key": "secrets-crypto",
   "name": "Secrets & Crypto",
   "cat": "infra",
   "ai_description": "Google KMS envelope, Secret Manager, HMAC-SHA256, TOTP secrets encrypted at rest"
  },
  {
   "key": "cicd",
   "name": "Secure CI/CD",
   "cat": "infra",
   "ai_description": "GitHub Actions reusable-workflow DAG, SHA-pinned images, immutable backups, tamper-evident remote exec, auto systemd rollback"
  },
  {
   "key": "quality",
   "name": "Quality & Graph",
   "cat": "quality",
   "ai_description": "~8233 unit/845 integration/175 E2E, JaCoCo/SpotBugs/PMD/OWASP, LegacyBugfix2026 23 bugs"
  }
 ],
 "leaves": [
  {
   "id": "app-core/active-cooperations-panel-role-scoped-read-projections",
   "name": "Active Cooperations Panel (role-scoped read projections)",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "src/main/java/com/sm/instagram/platform/activecooperations/",
   "ai_description": "Operational dashboard where companies triage applicants, watch in-flight collaborations and rate completed ones.",
   "why": "Field-level, view-driven serialization is exactly the data-minimization a privacy-conscious CTO wants - companies never…"
  },
  {
   "id": "app-core/applied-opportunity-application-aggregate",
   "name": "Applied Opportunity (Application) Aggregate",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "…a/com/sm/instagram/platform/appliedopportunities/AppliedOpportunity.java",
   "ai_description": "Join entity linking an influencer (User) to a campaign, carrying the lifecycle. DB @UniqueConstraint uk_influencer_opportunity enforces one application per influencer per campaign.",
   "why": "The unique constraint + optimistic version + dual ratings encode hard-won marketplace rules (no double-applications, no…"
  },
  {
   "id": "app-core/collaboration-lifecycle-state-machine",
   "name": "Collaboration Lifecycle State Machine",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "…va/com/sm/instagram/platform/appliedopportunities/OpportunityStatus.java",
   "ai_description": "12-state finite state machine governing every influencer-company collaboration (APPLIED -> ACCEPTED_BY_COMPANY -> ACCEPTED_BY_INFLUENCER -> CONTENT_SEND_TO_ACCEPT -> CONTENT_APPROVED ->…",
   "why": "The deepest moat in the codebase: an explicit, test-anchored state machine makes illegal transitions…"
  },
  {
   "id": "app-core/content-submission-approval-workflow",
   "name": "Content Submission & Approval Workflow",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "…m/instagram/platform/appliedopportunities/AppliedOpportunityContent.java",
   "ai_description": "How influencers submit deliverable content and companies approve/reject and track engagement.",
   "why": "Where the marketplace proves ROI - engagement metrics turn a collaboration into measurable campaign performance, and…"
  },
  {
   "id": "app-core/dynamic-applicant-filtering-engine-jpa-specification",
   "name": "Dynamic Applicant-Filtering Engine (JPA Specification)",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "…agram/platform/appliedopportunities/AppliedOpportunitySpecification.java",
   "ai_description": "Composable type-safe query builder turning a CoopFilter into a SQL WHERE over AppliedOpportunity. Implements Spring Data Specification;",
   "why": "The discovery/matchmaking layer - how a brand finds the right influencers (audience size + reputation) efficiently at…"
  },
  {
   "id": "app-core/multi-platform-social-connection-follower-sync",
   "name": "Multi-Platform Social Connection & Follower Sync",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "…com/sm/instagram/platform/usersocialconnection/UserSocialConnection.java",
   "ai_description": "Per-user links to social accounts across many platforms. Ties a User to a Platform + ServiceType storing socialUserId, followersCount, displayName, profilePictureUrl, isPrimary,…",
   "why": "Audience size is the currency of influencer marketing - this is the data powering follower-range campaign targeting and…"
  },
  {
   "id": "app-core/partnership-opportunity-campaign-domain",
   "name": "Partnership Opportunity (Campaign) Domain",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "src/main/java/com/sm/instagram/platform/partnershipopportunities/",
   "ai_description": "The campaign companies create and influencers browse. Entity PartnershipOpportunity.java + controller (@RequestMapping partnership-opportunity, create/update/patch/find/paged) + ~76KB…",
   "why": "The supply side of the marketplace - flexible enough to model cash OR barter deals, multi-platform reach and audience…"
  },
  {
   "id": "app-core/status-history-audit-trail",
   "name": "Status-History Audit Trail",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "…agram/platform/appliedopportunities/AppliedOpportunityStatusHistory.java",
   "ai_description": "Append-only ledger of every collaboration state transition: previousStatus, newStatus, acting User and/or raw changedByFirebaseId, @CreationTimestamp changedAt, optional changeReason and…",
   "why": "Disputes are inevitable in a two-sided marketplace (they said they approved it)."
  },
  {
   "id": "app-core/two-sided-rating-reputation-system",
   "name": "Two-Sided Rating / Reputation System",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "…main/java/com/sm/instagram/platform/appliedopportunities/RateStatus.java",
   "ai_description": "Symmetric independent ratings each party gives the other on a completed collaboration. RateStatus enum DEFAULT/POSITIVE/NEGATIVE with thumbs-up/down icons, success/danger color and i18n…",
   "why": "Reputation is the trust flywheel of any two-sided marketplace - it makes repeat business safe and is a direct input to…"
  },
  {
   "id": "app-core/unified-user-actor-model-account-status-state-machine",
   "name": "Unified User Actor Model + Account-Status State Machine",
   "domain": "app-core",
   "status": "VERIFIED",
   "path": "src/main/java/com/sm/instagram/platform/user/User.java",
   "ai_description": "Single User entity (@Table user) modeling all three actors via UserType (ADMIN/PENDING_ADMIN/INFLUENCER/COMPANY);",
   "why": "Two coordinated state machines (account + collaboration) plus token-version session invalidation and consent-version…"
  },
  {
   "id": "auth-identity/admin-totp-2fa-with-cloud-kms-encrypted-secrets-bcrypt-12-backup-codes",
   "name": "Admin TOTP 2FA with Cloud-KMS-encrypted secrets + BCrypt-12 backup codes",
   "domain": "auth-identity",
   "status": "VERIFIED",
   "path": "…in/java/com/sm/instagram/platform/auth/service/TwoFactorAuthService.java",
   "ai_description": "Mandatory Google-Authenticator 2FA for admins. Secrets minted via GoogleAuthenticator, stored KMS-encrypted (dedicated totp-secrets-key, region europe-central2/Warsaw, key ring…",
   "why": "Admin-account compromise is the #1 SaaS breach vector. KMS-managed key custody (no secret material in app or DB),…"
  },
  {
   "id": "auth-identity/instagram-meta-oauth-short-long-token-exchange-hmac-signed-meta-callbacks",
   "name": "Instagram/Meta OAuth: short->long token exchange + HMAC-signed Meta callbacks",
   "domain": "auth-identity",
   "status": "VERIFIED",
   "path": "…va/com/sm/instagram/platform/auth/social/instagram/InstagramService.java",
   "ai_description": "Sign in with Instagram for influencers. exchangeAuthCodeForProfile cleans code (strips Meta #_), gets short-lived token (api.instagram.com), upgrades to 60-day long-lived…",
   "why": "Meta App Review REQUIRES working deauthorize + data-deletion callbacks with valid signature verification - a gating…"
  },
  {
   "id": "auth-identity/instant-cross-device-revocation-token-version-419-silent-refresh-contract",
   "name": "Instant cross-device revocation (token-version) + 419 silent-refresh contract",
   "domain": "auth-identity",
   "status": "VERIFIED",
   "path": "…/common/authorization/JwtAuthenticationFilter.java (419 branch ~184-201)",
   "ai_description": "Each JWT carries tokenVersion; filter compares to Redis-cached current version (~1-2ms, no DB). Mismatch returns HTTP 419 (Session Expired), deliberately NOT 401.",
   "why": "Enterprise/IR requirement: revoke a compromised account everywhere instantly WITHOUT a logout storm for everyone else."
  },
  {
   "id": "auth-identity/server-mediated-firebase-auth-proxy-oobcode-lifecycle-anti-enumeration-transactional-compensation",
   "name": "Server-mediated Firebase auth proxy (oobCode lifecycle, anti-enumeration, transactional compensation)",
   "domain": "auth-identity",
   "status": "VERIFIED",
   "path": "…ava/com/sm/instagram/platform/auth/service/FirebaseAuthProxyService.java",
   "ai_description": "All Firebase Identity-Toolkit traffic (login/register/refresh/reset/verify/change/delete) brokered server-side with a service-account OAuth bearer; browser never talks to Firebase directly.",
   "why": "Email-enumeration and reset-timing leaks are textbook pentest findings, closed here by construction."
  },
  {
   "id": "auth-identity/session-hijack-detection-hmac-fingerprint-impossible-travel-geo-fencing",
   "name": "Session-Hijack Detection: HMAC fingerprint + impossible-travel geo-fencing",
   "domain": "auth-identity",
   "status": "VERIFIED",
   "path": "…/java/com/sm/instagram/platform/auth/service/SessionSecurityService.java",
   "ai_description": "Per-request HMAC-SHA256(ip:ua) fingerprint compared constant-time; exact User-Agent required; missing fingerprint rejected (fail-secure).",
   "why": "Account-takeover / anomalous-session defense sold as a paid premium add-on by IdP vendors (Okta/Entra…"
  },
  {
   "id": "auth-identity/step-up-re-authentication-redis-one-time-codes-single-use-token",
   "name": "Step-Up Re-Authentication (Redis one-time codes + single-use token)",
   "domain": "auth-identity",
   "status": "VERIFIED",
   "path": "…c/main/java/com/sm/instagram/platform/auth/stepup/StepUpAuthService.java",
   "ai_description": "Re-auth challenge before sensitive actions (password/email change). 6-digit email code stored in Redis as SHA-256 hash only (10-min TTL), emailed to last VERIFIED email;",
   "why": "Step-up re-auth is an explicit SOC2/ISO27001 control and PSD2-adjacent expectation."
  },
  {
   "id": "backups-dr/firestore-cloud-kms-for-sensitive-data-managed-geo-redundant-encrypted-off-host",
   "name": "Firestore + Cloud KMS for sensitive data (managed, geo-redundant, encrypted off-host)",
   "domain": "backups-dr",
   "status": "VERIFIED",
   "path": "…/main/java/com/sm/instagram/platform/auth/firebase/FirestoreService.java",
   "ai_description": "Most sensitive data (Instagram access tokens, TOTP 2FA secrets) deliberately stored in managed multi-region Firestore, envelope-encrypted via Google Cloud KMS (AES-256-GCM) with keys in…",
   "why": "Crown-jewel secrets and identity survive total VPS loss (data on Google plane, keys never on the box) and are…"
  },
  {
   "id": "backups-dr/immutable-backup-chain-chattr-i-replay-window-self-delete",
   "name": "Immutable backup chain (chattr +i + replay window + self-delete)",
   "domain": "backups-dr",
   "status": "VERIFIED",
   "path": ".github/scripts/remote/immutable-aware-backup.sh",
   "ai_description": "Zero-trust CI/CD + backup integrity chain: scripts and pre-deployment backups are locked with Linux chattr +i within ~1s of upload, SHA-256 bound via immutable .metadata, gated by a replay…",
   "why": "Deploy-time + supply-chain tamper-evidence most startups lack: kernel-enforced immutability + cryptographic checksum +…"
  },
  {
   "id": "backups-dr/ovh-vps-snapshot-dr-primary-db-backup-gap-honest",
   "name": "OVH VPS snapshot DR primary + DB-backup gap (honest)",
   "domain": "backups-dr",
   "status": "DOC_ONLY",
   "path": "ansible/QUICK-DEPLOYMENT-GUIDE.md",
   "ai_description": "Documented operator-driven full-system DR: take an OVH VPS snapshot before risky changes, restore the whole box (OS + Docker volumes incl Postgres data) as the fastest recovery path.",
   "why": "Pragmatic no-extra-cost full-system rollback a small team can actually operate;"
  },
  {
   "id": "backups-dr/pre-deployment-backup-with-integrity-verification-retention",
   "name": "Pre-deployment backup with integrity verification + retention",
   "domain": "backups-dr",
   "status": "VERIFIED",
   "path": ".github/scripts/remote/create-pre-deployment-backup.sh",
   "ai_description": "Mandatory secure-logged snapshot of deployment/ + runtime/ taken before every deploy. Counts source files/size, copies (incl dotfiles), verifies integrity (file-count must match, size…",
   "why": "Roll-forward deploys are only safe with a verified restorable snapshot per release;"
  },
  {
   "id": "backups-dr/redis-sentinel-ha-failover-cache-rate-limit-tier-resilience",
   "name": "Redis Sentinel HA failover (cache/rate-limit tier resilience)",
   "domain": "backups-dr",
   "status": "VERIFIED",
   "path": "deployment/prod/sentinel-entrypoint.sh",
   "ai_description": "Rate-limit/cache tier runs Redis master (AOF appendonly, 1GB LRU) + a Sentinel that auto-detects master failure (down-after 5s, failover-timeout 10s) on a static-IP Docker network.",
   "why": "HA thinking beyond a single process: automatic failover means a Redis crash does not take down auth throttling or…"
  },
  {
   "id": "backups-dr/versioned-gcs-bucket-lifecycle-live-loki-object-store-backup-plane",
   "name": "Versioned GCS bucket + lifecycle (live Loki object-store backup plane)",
   "domain": "backups-dr",
   "status": "VERIFIED",
   "path": "deployment/loki/setup-gcs-bucket.sh",
   "ai_description": "Hardened GCS bucket that is the live object store backend for Loki: object versioning ON (overwrites/deletes recoverable), 30-day lifecycle (7-day for tmp/), public-access-prevention…",
   "why": "Durable, versioned, delete-protected object storage is the backbone of a credible log-retention/forensic story…"
  },
  {
   "id": "billing/fakturowniaadapter",
   "name": "FakturowniaAdapter",
   "domain": "billing",
   "role": "implementation",
   "status": "LIVE",
   "path": "…com/sm/instagram/platform/subscription/invoicing/FakturowniaAdapter.java",
   "ai_description": "Fakturownia REST adapter implementing InvoicingPort; creates VAT-exempt invoices (tax 'zw', exempt_tax_kind 'art113') for subscription payments."
  },
  {
   "id": "billing/invoicerecord",
   "name": "InvoiceRecord",
   "domain": "billing",
   "role": "implementation",
   "status": "LIVE",
   "path": "…in/java/com/sm/instagram/platform/subscription/entity/InvoiceRecord.java",
   "ai_description": "JPA entity tracking each invoice through PENDING/SENT/FAILED/DEAD_LETTER, linked to user, billing period and fakturownia_invoice_id."
  },
  {
   "id": "billing/invoiceretrycronjob",
   "name": "InvoiceRetryCronJob",
   "domain": "billing",
   "role": "lifecycle",
   "status": "LIVE",
   "path": "…ava/com/sm/instagram/platform/subscription/cron/InvoiceRetryCronJob.java",
   "ai_description": "Every-15-minutes ShedLock cron (lockAtMostFor 14m) delegating to InvoiceRetryService. Bean-gated by app.payments.enabled so invoicing only runs when payments are on."
  },
  {
   "id": "billing/invoiceretryservice",
   "name": "InvoiceRetryService",
   "domain": "billing",
   "role": "implementation",
   "status": "LIVE",
   "path": "…om/sm/instagram/platform/subscription/invoicing/InvoiceRetryService.java",
   "ai_description": "Retries invoices stuck in FAILED for over 15 minutes and promotes exhausted ones to DEAD_LETTER. Per-invoice error isolation keeps one bad record from blocking the batch."
  },
  {
   "id": "billing/invoicingport",
   "name": "InvoicingPort",
   "domain": "billing",
   "role": "implementation",
   "status": "LIVE",
   "path": "…java/com/sm/instagram/platform/subscription/invoicing/InvoicingPort.java",
   "ai_description": "Port interface for invoice generation with record-based InvoiceRequest/InvoiceResult contracts. Abstracts the invoicing provider so business logic never touches Fakturownia specifics."
  },
  {
   "id": "billing/stripewebhookcontroller",
   "name": "StripeWebhookController",
   "domain": "billing",
   "role": "controller",
   "status": "LIVE",
   "path": "…m/sm/instagram/platform/subscription/stripe/StripeWebhookController.java",
   "ai_description": "Receives POST /webhooks/stripe and verifies the Stripe-Signature header via Webhook.constructEvent before any processing."
  },
  {
   "id": "billing/stripewebhookhandler",
   "name": "StripeWebhookHandler",
   "domain": "billing",
   "role": "implementation",
   "status": "LIVE",
   "path": "…/com/sm/instagram/platform/subscription/stripe/StripeWebhookHandler.java",
   "ai_description": "Routes verified Stripe events to SubscriptionService with three resilience layers: fast-path existsByStripeEventId, the subscription_event_stripe_unique DB constraint as the real…"
  },
  {
   "id": "billing/subscriptionevent",
   "name": "SubscriptionEvent",
   "domain": "billing",
   "role": "implementation",
   "status": "LIVE",
   "path": "…ava/com/sm/instagram/platform/subscription/entity/SubscriptionEvent.java",
   "ai_description": "Append-only ledger entity storing the unique Stripe event id and typed lifecycle events — the durable idempotency record for webhook processing."
  },
  {
   "id": "billing/subscriptionperiodprocessorcronjob",
   "name": "SubscriptionPeriodProcessorCronJob",
   "domain": "billing",
   "role": "lifecycle",
   "status": "LIVE",
   "path": "…agram/platform/subscription/cron/SubscriptionPeriodProcessorCronJob.java",
   "ai_description": "Daily 04:00 ShedLock cron. Paid branches (expired trials, downgrades) are guarded inline while FREE-plan billing-period rollover always runs — deliberately NOT bean-gated."
  },
  {
   "id": "billing/subscriptionservice",
   "name": "SubscriptionService",
   "domain": "billing",
   "role": "implementation",
   "status": "LIVE",
   "path": "…ain/java/com/sm/instagram/platform/subscription/SubscriptionService.java",
   "ai_description": "Core billing service implementing the 10-state/56-transition subscription lifecycle (trial, upgrade, downgrade, payment failure, terms versioning)."
  },
  {
   "id": "cicd/autorollbackworkflow",
   "name": "AutoRollbackWorkflow",
   "domain": "cicd",
   "role": "lifecycle",
   "status": "LIVE",
   "path": ".github/workflows/auto-rollback-systemd.yml",
   "ai_description": "GitHub Actions workflow that invokes the systemd rollback path when post-deployment validation fails."
  },
  {
   "id": "cicd/deployandsecure",
   "name": "DeployAndSecure",
   "domain": "cicd",
   "role": "security",
   "status": "LIVE",
   "path": ".github/scripts/remote/deploy-and-secure.sh",
   "ai_description": "v6.0 deployment script implementing the full immutability chain — every deployed file is made immutable to eliminate tamper windows; sources .env and the secure-logger library before acting."
  },
  {
   "id": "cicd/envchecker",
   "name": "EnvChecker",
   "domain": "cicd",
   "role": "diagnostics",
   "status": "LIVE",
   "path": ".github/scripts/remote/env-checker.sh",
   "ai_description": "Sourced 'Gold Standard Lite V2' environment validator that gates deployment scripts on required variables with standardized logging."
  },
  {
   "id": "cicd/immutabilitychaindoc",
   "name": "ImmutabilityChainDoc",
   "domain": "cicd",
   "role": "security",
   "status": "LIVE",
   "path": "deployment/docs/COMPLETE_IMMUTABILITY_CHAIN.md",
   "ai_description": "Design doc mapping the four attack windows (scripts on disk, admin home, copy race, logger dependency) and the chattr +i chain that closes each across runner, admin home and deployment dir."
  },
  {
   "id": "cicd/mavenqualitygates",
   "name": "MavenQualityGates",
   "domain": "cicd",
   "role": "configuration",
   "status": "LIVE",
   "path": "pom.xml",
   "ai_description": "Build-time gate stack: enforcer (Java 21 range, banned commons-logging), JaCoCo coverage, OWASP dependency-check failing on CVSS>=7, SpotBugs+FindSecBugs at effort Max/threshold Low with…"
  },
  {
   "id": "cicd/predeploymentbackup",
   "name": "PreDeploymentBackup",
   "domain": "cicd",
   "role": "lifecycle",
   "status": "LIVE",
   "path": ".github/scripts/remote/create-pre-deployment-backup.sh",
   "ai_description": "Captures an immutability-aware backup of the running deployment before any new release lands — the restore point for rollback."
  },
  {
   "id": "cicd/proddeploymentworkflow",
   "name": "ProdDeploymentWorkflow",
   "domain": "cicd",
   "role": "lifecycle",
   "status": "LIVE",
   "path": ".github/workflows/backend-deployment-prod.yml",
   "ai_description": "Production pipeline composing reusable workflows: config validation, Maven/Docker build, pre-deployment backup, deploy-and-secure and reload-and-validate."
  },
  {
   "id": "cicd/securescriptupload",
   "name": "SecureScriptUpload",
   "domain": "cicd",
   "role": "security",
   "status": "LIVE",
   "path": ".github/scripts/runner/secure-script-upload.sh",
   "ai_description": "Runner-side upload step that applies chattr +i immediately after scp, closing the on-disk modification window between upload and execution."
  },
  {
   "id": "cicd/systemdrollback",
   "name": "SystemdRollback",
   "domain": "cicd",
   "role": "lifecycle",
   "status": "LIVE",
   "path": ".github/scripts/remote/execute-systemd-rollback.sh",
   "ai_description": "Systemd-aware restore from the pre-deployment backup. Refuses to execute if the script file is older than 10 minutes (timestamp defense-in-depth) and cleans up after itself."
  },
  {
   "id": "cicd/validateandexecciscript",
   "name": "ValidateAndExecCiScript",
   "domain": "cicd",
   "role": "security",
   "status": "LIVE",
   "path": ".github/scripts/remote/validate-and-exec-ci-script.sh",
   "ai_description": "V10.1 execution wrapper that validates CI scripts before running them under chattr +i immutability protection, temporarily lifts immutability on dependencies, then strips all flags…"
  },
  {
   "id": "frontend-v2/checkitoutfegreenfield",
   "name": "CheckItOutFeGreenfield",
   "domain": "frontend-v2",
   "role": "implementation",
   "status": "PLANNED-PUBLIC",
   "path": "C:/Users/Norbert/IdeaProjects/checkItOut-fe-greenfield",
   "ai_description": "Greenfield Angular Material rewrite of the Fuse-based frontend with an OpenAPI-generated client, committed visual-parity baselines and route-by-route strangler cutover."
  },
  {
   "id": "geo-security/dual-cache-redisgeolocationcache-inmemorygeolocationcache",
   "name": "Dual cache: RedisGeoLocationCache + InMemoryGeoLocationCache",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…tionCache.java + InMemoryGeoLocationCache.java (+ GeoLocationCache.java)",
   "ai_description": "One GeoLocationCache interface, two @ConditionalOnProperty(storage.mode) impls. Redis: HASHED IP keys (no raw IPs), JSON values with 7-day TTL (GDPR auto-expiry), travel lists 30-day TTL,…",
   "why": "Deployment flexibility lowers buyer friction - same code runs on a Redis cluster or a single VM via one config flag."
  },
  {
   "id": "geo-security/geo-test-verification-suite-175-unit-assertions-e2e-cucumber",
   "name": "Geo test & verification suite (175 unit assertions + E2E Cucumber)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…s/features/admin-geoip-analysis.feature + e2e/steps/AdminGeoIpSteps.java",
   "ai_description": "175 geo-specific @Test assertions across three unit suites plus a full E2E Cucumber feature exercising the admin analysis flow end-to-end.",
   "why": "Test depth is the best due-diligence proxy for 'can we change this safely?'."
  },
  {
   "id": "geo-security/geodistancecalculator-standalone-haversine-utility",
   "name": "GeoDistanceCalculator (standalone Haversine utility)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…in/java/com/sm/instagram/platform/common/util/GeoDistanceCalculator.java",
   "ai_description": "Pure, stateless, instantiation-proof utility (EARTH_RADIUS_KM=6371.0) with calculateDistanceKm(lat1,lon1,lat2,lon2) and isWithinRadius(...).",
   "why": "Small but the mathematically correct great-circle core the whole risk engine and any future nearby/geofence feature…"
  },
  {
   "id": "geo-security/geoipadmincontroller-admin-ops-live-travel-analysis-api",
   "name": "GeoIpAdminController (admin ops + live travel-analysis API)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "src/main/java/com/sm/instagram/platform/admin/GeoIpAdminController.java",
   "ai_description": "Six admin-only (@PreAuthorize ADMIN), Swagger-annotated endpoints under /admin/geoip: GET /metrics, GET /lookup/{ip} (IPv4-validated), GET /my-location (multi-header client-IP extraction),…",
   "why": "Operability sells. A locked-down audited observability surface lets ops answer 'why was this user blocked?' in seconds…"
  },
  {
   "id": "geo-security/geoipstorageservice-firebase-distribution-of-the-61mb-db",
   "name": "GeoIpStorageService (Firebase distribution of the 61MB DB)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…/java/com/sm/instagram/platform/common/security/GeoIpStorageService.java",
   "ai_description": "Centralized license-protected DB distribution via a PRIVATE Firebase/GCS bucket (europe-central2).",
   "why": "The scale-horizontally-without-abusing-your-vendor story: one node fetches from MaxMind, the rest pull from your…"
  },
  {
   "id": "geo-security/geolocation-model-geolocationservice-geolocationcache-interfaces",
   "name": "GeoLocation model + GeoLocationService/GeoLocationCache interfaces",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…GeoLocation.java + GeoLocationService.java + geoip/GeoLocationCache.java",
   "ai_description": "The clean contract layer. GeoLocation DTO (Lombok builder): ip, country/code, city, region, lat/lon, postal, timezone, ISP, isVpn/isProxy/isTor, plus an unknown(ip) sentinel and isKnown().",
   "why": "Good seams. Interfaces plus a thoughtful unknown sentinel are why the subsystem is testable, mockable, and extensible…"
  },
  {
   "id": "geo-security/geolocationfacade-orchestrator",
   "name": "GeoLocationFacade (orchestrator)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…a/com/sm/instagram/platform/common/security/geoip/GeoLocationFacade.java",
   "ai_description": "Primary GeoLocationService bean. Cache-first lookup (cache miss -> MaxMind async -> convert -> cache put).",
   "why": "Textbook facade + DI: the app talks to one stable interface while storage backend, DB engine, and travel logic stay…"
  },
  {
   "id": "geo-security/geolocationgdprservice-geolocationgdprcontroller-art-17-20-5-13",
   "name": "GeoLocationGdprService + GeoLocationGdprController (Art 17/20/5/13)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…on/security/GeoLocationGdprService.java + GeoLocationGdprController.java",
   "ai_description": "Full GDPR rights for location data under /gdpr/location/*: Art 17 erasure (DELETE /ip/{ip}, /user/{userId});",
   "why": "GDPR is a hard gate for EU SaaS and a board-level risk. Automated, audited, per-article self-service DSAR tooling with…"
  },
  {
   "id": "geo-security/maxminddatabaseservice-61mb-geolite2-city-mmdb",
   "name": "MaxMindDatabaseService + 61MB GeoLite2-City.mmdb",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…ip/MaxMindDatabaseService.java + checkItOut-be2/geoip/GeoLite2-City.mmdb",
   "ai_description": "Full lifecycle of the MaxMind GeoLite2-City DB (61,349,557 bytes, committed). PostConstruct load-or-download;",
   "why": "A 61MB, weekly-auto-refreshed, atomically hot-swapped IP->geo DB is hardened infrastructure, not a rate-limited API…"
  },
  {
   "id": "geo-security/maxmindstartupvalidator-boot-time-self-test",
   "name": "MaxMindStartupValidator (boot-time self-test)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…a/com/sm/instagram/platform/common/security/MaxMindStartupValidator.java",
   "ai_description": "Startup smoke test on ApplicationReadyEvent (non-fatal). Resolves the server external IP with redundant fallbacks (ipify/ipinfo/amazonaws/icanhazip), geolocates it, asserts 8.8.8.8 resolves…",
   "why": "Self-validating infrastructure: the startup log immediately tells ops whether geo-security is functional (DB loaded,…"
  },
  {
   "id": "geo-security/sessionsecurityservice-impossible-travel-fail-closed-circuit-breaker",
   "name": "SessionSecurityService impossible-travel + fail-closed circuit breaker",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…/java/com/sm/instagram/platform/auth/service/SessionSecurityService.java",
   "ai_description": "The wiring point where geo meets auth. On a changed session IP it calls isImpossibleTravel -> GeoLocationFacade.checkImpossibleTravel (500ms budget).",
   "why": "Impossible-travel detection is a paid feature in Okta/Auth0/Entra."
  },
  {
   "id": "geo-security/travelpatternservice-3-tier-haversine-risk-0-100-vpn-tor",
   "name": "TravelPatternService (3-tier + Haversine + risk 0-100 + VPN/Tor)",
   "domain": "geo-security",
   "status": "VERIFIED",
   "path": "…om/sm/instagram/platform/common/security/geoip/TravelPatternService.java",
   "ai_description": "The detection brain. Tier 1 same-city always allow (name match or <50km); Tier 2 same-country speed check vs max-speed (500km/h);",
   "why": "A self-contained, dependency-light fraud-risk engine. The tiered approach kills false-positive lockouts (the feature…"
  },
  {
   "id": "hardening/drop-by-default-firewall-privilege-reduction",
   "name": "DROP-by-default firewall + privilege reduction",
   "domain": "hardening",
   "status": "VERIFIED",
   "path": "ansible/roles/15-final-hardening/files/apply-firewall-rules.sh",
   "ai_description": "Deny-all iptables baseline: flush, INPUT/FORWARD policy DROP (v4+v6), allow loopback + ESTABLISHED,RELATED, open only 22/80/443 + rate-limited ICMP;",
   "why": "Textbook default-DROP + minimal port surface + flood/scan mitigation, plus the rare 'remove root-equivalent group…"
  },
  {
   "id": "hardening/github-ip-ssh-allow-list-staged",
   "name": "GitHub-IP SSH allow-list (STAGED)",
   "domain": "hardening",
   "status": "STAGED",
   "path": "deployment/config/update-github-ips.sh",
   "ai_description": "Infra to restrict CI/CD-originated SSH to GitHub Actions egress ranges. update-github-ips.sh creates ipset github-v4 (hash:net inet) + github-v6, fetches api.github.com/meta, ingests…",
   "why": "The hard part -- discovering/normalizing/continuously refreshing GitHub's egress ranges into a kernel ipset on a cron…"
  },
  {
   "id": "hardening/kernel-sysctl-hardening-baseline",
   "name": "Kernel sysctl hardening baseline",
   "domain": "hardening",
   "status": "VERIFIED",
   "path": "ansible/inventory/group_vars/all.yml (sysctl_parameters)",
   "ai_description": "~30-key kernel baseline applied + verified idempotently. Network anti-spoof (rp_filter=1, accept_source_route=0, accept_redirects=0 v4+v6, log_martians=1, ip_forward=0);",
   "why": "Exactly the controls CIS Benchmarks / DISA STIGs enumerate for a Linux host -- in version control, so every box stood…"
  },
  {
   "id": "hardening/least-privilege-sudoers-allow-list-explicit-deny",
   "name": "Least-privilege sudoers (allow-list + explicit deny)",
   "domain": "hardening",
   "status": "VERIFIED",
   "path": "…am-{prod,test}-deploy, 90-instagram-scripts-admin, 95-ubuntu-docker-cicd",
   "ai_description": "849 lines of hand-curated sudoers across 3 deploy identities: positive allow-list of EXACT pinned commands (no wildcards on dangerous verbs) plus a negative !Cmnd_Alias deny tier…",
   "why": "Least privilege (SOC-2 CC6.1 / ISO 27001 A.9) implemented as 849 lines of enforced, syntax-gated, audit-logged config…"
  },
  {
   "id": "hardening/os-level-immutability-chain-chattr-i",
   "name": "OS-level immutability chain (chattr +i)",
   "domain": "hardening",
   "status": "VERIFIED",
   "path": "ansible/roles/14-security/tasks/immutable.yml",
   "ai_description": "Zero-trust-on-disk posture: critical secrets, both systemd unit files, and the 3 sudoers policies themselves are flagged chattr +i (verified via lsattr).",
   "why": "'Even root cannot quietly tamper with our deploy artifacts' is a concrete supply-chain hardening story."
  },
  {
   "id": "hardening/ssh-hardening-template-yubikey-gated-break-glass",
   "name": "SSH hardening template (YubiKey-gated break-glass)",
   "domain": "hardening",
   "status": "VERIFIED",
   "path": "ansible/roles/01-base-system/templates/sshd_hardening.conf.j2",
   "ai_description": "Opinionated sshd policy: root off, password off, closed AllowUsers set, only AEAD/CTR ciphers + ETM MACs + curve25519 KEX (no CBC/SHA-1), MaxAuthTries 3, LogLevel VERBOSE.",
   "why": "Phishing-resistant, hardware-backed admin access is the gold standard auditors want on the break-glass path."
  },
  {
   "id": "legal-consent/consentcookieservice",
   "name": "ConsentCookieService",
   "domain": "legal-consent",
   "role": "security",
   "status": "LIVE",
   "path": "src/main/java/com/sm/instagram/platform/legal/ConsentCookieService.java",
   "ai_description": "Issues HMAC-signed consent-proof cookies using a DEDICATED secret separate from the session-cookie HMAC, preventing cross-contamination and allowing independent rotation."
  },
  {
   "id": "legal-consent/consentenforcementcronjob",
   "name": "ConsentEnforcementCronJob",
   "domain": "legal-consent",
   "role": "lifecycle",
   "status": "LIVE",
   "path": "…main/java/com/sm/instagram/platform/legal/ConsentEnforcementCronJob.java",
   "ai_description": "Daily 02:00 ShedLock cron blocking users who have not re-accepted updated legal terms within the 38-day grace period."
  },
  {
   "id": "legal-consent/consentrecord",
   "name": "ConsentRecord",
   "domain": "legal-consent",
   "role": "implementation",
   "status": "LIVE",
   "path": "src/main/java/com/sm/instagram/platform/legal/ConsentRecord.java",
   "ai_description": "Consent-proof entity with nullable user for anonymous cookie consents that get linked to the account after registration completes."
  },
  {
   "id": "legal-consent/consentservice",
   "name": "ConsentService",
   "domain": "legal-consent",
   "role": "implementation",
   "status": "LIVE",
   "path": "src/main/java/com/sm/instagram/platform/consent/ConsentService.java",
   "ai_description": "GDPR consent module with versioned consent definitions, an immutable user_consent event log, and a user_current_consent projection for fast status queries."
  },
  {
   "id": "legal-consent/deferreddeletioncronjob",
   "name": "DeferredDeletionCronJob",
   "domain": "legal-consent",
   "role": "lifecycle",
   "status": "LIVE",
   "path": "…in/java/com/sm/instagram/platform/auth/cron/DeferredDeletionCronJob.java",
   "ai_description": "Daily 03:00 ShedLock cron re-checking deferred deletion requests and executing the account cascade delete once active collaborations end."
  },
  {
   "id": "legal-consent/hmacutils",
   "name": "HmacUtils",
   "domain": "legal-consent",
   "role": "security",
   "status": "LIVE",
   "path": "src/main/java/com/sm/instagram/platform/auth/filter/HmacUtils.java",
   "ai_description": "HmacSHA256 signing plus constant-time comparison utility underpinning consent and session cookie integrity."
  },
  {
   "id": "legal-consent/instagramdatadeletionservice",
   "name": "InstagramDataDeletionService",
   "domain": "legal-consent",
   "role": "implementation",
   "status": "LIVE",
   "path": "…com/sm/instagram/platform/auth/service/InstagramDataDeletionService.java",
   "ai_description": "Handles Meta data-deletion callbacks: immediate archiveUser() when no active collaborations exist (Case A), or a deferred pending_data_deletion_request queue (Case B)."
  },
  {
   "id": "legal-consent/legalconsentservice",
   "name": "LegalConsentService",
   "domain": "legal-consent",
   "role": "implementation",
   "status": "LIVE",
   "path": "src/main/java/com/sm/instagram/platform/legal/LegalConsentService.java",
   "ai_description": "Orchestrates the terms-acceptance lifecycle: records consent proof, computes the 38-day grace window, and blocks/unblocks accounts through UserAccountOrchestrator."
  },
  {
   "id": "legal-consent/legalcontroller",
   "name": "LegalController",
   "domain": "legal-consent",
   "role": "controller",
   "status": "LIVE",
   "path": "src/main/java/com/sm/instagram/platform/legal/LegalController.java",
   "ai_description": "Public REST surface for legal documents and consent capture, covering anonymous cookie-banner consents and authenticated terms acceptance."
  },
  {
   "id": "legal-consent/noconsentaccountcleanupcronjob",
   "name": "NoConsentAccountCleanupCronJob",
   "domain": "legal-consent",
   "role": "lifecycle",
   "status": "LIVE",
   "path": "…java/com/sm/instagram/platform/legal/NoConsentAccountCleanupCronJob.java",
   "ai_description": "Weekly Sunday cron archiving accounts with ZERO consent records past the grace period — GDPR Art. 6 lawful-basis hygiene and Art. 5(2) accountability evidence."
  },
  {
   "id": "network-perimeter/cloudflarerealipupdate",
   "name": "CloudflareRealIpUpdate",
   "domain": "network-perimeter",
   "role": "lifecycle",
   "status": "LIVE",
   "path": "deployment/config/cloudflare-ip-update.sh",
   "ai_description": "Daily cron script fetching Cloudflare IPv4/IPv6 ranges and regenerating the set_real_ip_from config (01-cloudflare.conf) with timestamped backups, last 30 kept."
  },
  {
   "id": "network-perimeter/corsproperties",
   "name": "CorsProperties",
   "domain": "network-perimeter",
   "role": "configuration",
   "status": "LIVE",
   "path": "src/main/java/com/sm/instagram/platform/config/CorsProperties.java",
   "ai_description": "Typed cors.* configuration (origins, methods, headers, credentials, 24h preflight max-age) consumed by the CorsConfigurationSource bean."
  },
  {
   "id": "network-perimeter/mtlslokiconfig",
   "name": "MtlsLokiConfig",
   "domain": "network-perimeter",
   "role": "security",
   "status": "LIVE",
   "path": "deployment/config/nginx-refactored/conf.d/mtls-loki.conf",
   "ai_description": "Mutual-TLS configuration gating the loki.checkitout.app monitoring vhost so only client-certificate holders reach the log store."
  },
  {
   "id": "network-perimeter/nginxansiblerole",
   "name": "NginxAnsibleRole",
   "domain": "network-perimeter",
   "role": "configuration",
   "status": "LIVE",
   "path": "ansible/roles/08-nginx",
   "ai_description": "Ansible role deploying nginx.conf, 9 modular conf.d configs and 4 site configs from deployment/config/nginx-refactored, with config test, backup, Let's Encrypt SSL and mTLS-for-Loki tasks."
  },
  {
   "id": "network-perimeter/nginxratelimiting",
   "name": "NginxRateLimiting",
   "domain": "network-perimeter",
   "role": "security",
   "status": "LIVE",
   "path": "deployment/config/nginx-refactored/conf.d/02-rate-limiting.conf",
   "ai_description": "Six limit_req zones (general/api 30r/s, login 20r/m, upload 15r/m, strict 1r/s, support 5r/m) plus connection limits, all keyed on $real_ip so clients behind Cloudflare do not share one…"
  },
  {
   "id": "network-perimeter/nginxsecurityheaders",
   "name": "NginxSecurityHeaders",
   "domain": "network-perimeter",
   "role": "security",
   "status": "LIVE",
   "path": "deployment/config/nginx-refactored/conf.d/03-security.conf",
   "ai_description": "Modular security headers and server-hardening directives (03-security.conf plus security-headers.conf) included by the vhosts."
  },
  {
   "id": "network-perimeter/nginxtlsconfig",
   "name": "NginxTlsConfig",
   "domain": "network-perimeter",
   "role": "security",
   "status": "LIVE",
   "path": "deployment/config/nginx-refactored/conf.d/04-ssl.conf",
   "ai_description": "TLS 1.2/1.3 only with a modern ECDHE/CHACHA20 cipher suite, shared session cache and session tickets disabled."
  },
  {
   "id": "network-perimeter/productionsiteconfig",
   "name": "ProductionSiteConfig",
   "domain": "network-perimeter",
   "role": "configuration",
   "status": "LIVE",
   "path": "deployment/config/nginx-refactored/sites-available/checkitout.app.conf",
   "ai_description": "checkitout.app vhost: HTTP-to-HTTPS and www-to-apex 301s, http2, Let's Encrypt certificates with dhparams, per-location rate-limit zones and cloudflare log format."
  },
  {
   "id": "network-perimeter/websecurityconfiguration",
   "name": "WebSecurityConfiguration",
   "domain": "network-perimeter",
   "role": "security",
   "status": "LIVE",
   "path": "…sm/instagram/platform/common/authorization/WebSecurityConfiguration.java",
   "ai_description": "Spring SecurityFilterChain with JWT authentication, banned-user, consent-enforcement and email-verification filters; explicit public-endpoint allowlist;"
  },
  {
   "id": "observability/ansible-10-monitoring-role-vault-secret",
   "name": "Ansible 10-monitoring role + Vault secret",
   "domain": "observability",
   "status": "VERIFIED",
   "path": "ansible/roles/10-monitoring/tasks/main.yml",
   "ai_description": "IaC that deploys the whole stack idempotently from deployment/loki (single source of truth): sequences loki-config -> alloy-config -> compose -> conditional mTLS cert gen -> verify.",
   "why": "Observability stack is not a pet: destroy the host and make deploy rebuilds the secured log platform from code, with…"
  },
  {
   "id": "observability/gcs-storage-backend-bootstrap-versioned-lifecycle-governed",
   "name": "GCS storage backend bootstrap (versioned, lifecycle-governed)",
   "domain": "observability",
   "status": "VERIFIED",
   "path": "deployment/loki/setup-gcs-bucket.sh",
   "ai_description": "Provisions the GCS backing store: uniform bucket-level access + versioning, 30-day delete lifecycle for loki_index_/loki- prefixes (defense-in-depth alongside Loki compactor), Public Access…",
   "why": "Storage governance done properly: private-by-default, versioned, lifecycle-bounded, self-audited, least-privilege SA."
  },
  {
   "id": "observability/grafana-alloy-collector-sealed-journal-6-pipelines",
   "name": "Grafana Alloy collector (sealed-journal, 6 pipelines)",
   "domain": "observability",
   "status": "VERIFIED",
   "path": "deployment/loki/alloy-config.alloy",
   "ai_description": "Grafana Alloy v1.4.3 (Promtail successor) reads the systemd journal as JSON and fans every entry through 6 parsing pipelines (Spring Boot with trace_id/span_id + multiline stack traces,…",
   "why": "Structured-logging ELT (not tail-a-file): trace-correlated, low-cardinality, multi-service streams plus security…"
  },
  {
   "id": "observability/live-custom-grafana-dashboards-ops-perf-prod-test",
   "name": "LIVE custom Grafana dashboards (ops + perf, PROD & TEST)",
   "domain": "observability",
   "status": "VERIFIED LIVE",
   "path": "…perf-test, checkitout-api-metrics, app-errors-001, traffic-endpoints-001",
   "ai_description": "Purpose-built CheckItOut dashboards (not just stock Grafana Cloud): Operations Center + Traffic&Performance split per environment (PROD requests/errors/security/performance;",
   "why": "Data is operationalized - separate prod/test cockpits, per-endpoint latency, payment-flow visibility."
  },
  {
   "id": "observability/live-grafana-alerting-7-rules-incl-pentest-security-detectors",
   "name": "LIVE Grafana alerting - 7 rules incl. pentest/security detectors",
   "domain": "observability",
   "status": "VERIFIED LIVE",
   "path": "Grafana folder CheckItOut Alerts (cfgze8vote8lcd)",
   "ai_description": "7 Grafana-managed alert rules (folder CheckItOut Alerts), all observed normal/ok with sub-minute eval: Application Down-No Logs (5m crash detector), High Error Rate-Production (>5/10m),…",
   "why": "Threat detection built ON the logging pipeline - one LogQL query + threshold."
  },
  {
   "id": "observability/live-self-hosted-loki-datasource-in-grafana",
   "name": "LIVE self-hosted Loki datasource in Grafana",
   "domain": "observability",
   "status": "VERIFIED LIVE",
   "path": "… checkitoutapp / datasource Loki-CheckItOut uid bewat6pbawmioa (default)",
   "ai_description": "The self-hosted Loki is wired into Grafana as the DEFAULT datasource (uid bewat6pbawmioa, type loki) and is actively serving the journal stream.",
   "why": "Removes all 'is it actually running?' doubt - the infra is a live, queried, default datasource feeding real dashboards…"
  },
  {
   "id": "observability/loki-3-5-3-backend-gcs-backed-30-day-retention",
   "name": "Loki 3.5.3 backend (GCS-backed, 30-day retention)",
   "domain": "observability",
   "status": "VERIFIED",
   "path": "deployment/loki/loki-config.yaml",
   "ai_description": "Single-binary Loki 3.5.3 (target=all) storing chunks+TSDB index in GCS bucket checkitout-logs-eu, schema v13.",
   "why": "Correctly-operated Loki v13/3.5.x with object-storage offload (carries real version-migration scar comments)."
  },
  {
   "id": "observability/mtls-pki-bootstrap-ca-server-4-client-certs-crl",
   "name": "mTLS PKI bootstrap (CA + server + 4 client certs + CRL)",
   "domain": "observability",
   "status": "VERIFIED",
   "path": "deployment/loki/setup-certificates.sh",
   "ai_description": "One-shot script standing up the whole CA: 4096-bit 10-year CA, 2048-bit server cert for loki.checkitout.app (SANs loki/localhost/127.0.0.1), 4 named client certs (grafana-cloud, alloy,…",
   "why": "Full private-PKI lifecycle without a paid service - issue, distribute, verify, and crucially REVOKE (CRL + revoke…"
  },
  {
   "id": "observability/nginx-mtls-reverse-proxy-edge-loki-checkitout-app",
   "name": "nginx mTLS reverse-proxy edge (loki.checkitout.app)",
   "domain": "observability",
   "status": "VERIFIED",
   "path": "…loyment/config/nginx-refactored/sites-available/loki.checkitout.app.conf",
   "ai_description": "nginx 1.24 vhost: only public door to Loki. ssl_verify_client on, depth 2 against private CA; map authorizes exact CNs grafana-cloud@CheckItOut + alloy@CheckItOut;",
   "why": "Zero-trust log ingest: mutual TLS with a private CA, CN-based authorization, per-endpoint policy, admin plane on…"
  },
  {
   "id": "observability/systemd-unit-docker-compose-runtime-packaging",
   "name": "systemd unit + docker-compose runtime packaging",
   "domain": "observability",
   "status": "VERIFIED",
   "path": "deployment/loki/docker-compose.yml",
   "ai_description": "Operational packaging: docker-compose runs init-loki (busybox fixes /loki ownership to UID 10001) -> Loki 3.5.3 bound 127.0.0.1:3100 with /ready healthcheck + GOMEMLIMIT OOM guard -> Alloy…",
   "why": "Boot-persistent, self-healing (Restart=always + healthchecks + depends_on ordering), memory-bounded, and even the…"
  },
  {
   "id": "provisioning/app-lifecycle-07-systemd-13-automation-06-scripts",
   "name": "App lifecycle (07-systemd + 13-automation + 06-scripts)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…atform-{prod,test}.service.j2,files/flask-auth-app.{py,service},tasks/*}",
   "ai_description": "systemd units auto-start test/prod stacks on boot (each env is a service wrapping docker compose); a small Flask auth helper service; cron + systemd-timer automation; logrotate;",
   "why": "Survives reboots unattended; scheduled maintenance (backups, log rotation) codified, not cron-on-a-prayer."
  },
  {
   "id": "provisioning/base-system-hardening-01-base-system",
   "name": "Base-system hardening (01-base-system)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "ansible/roles/01-base-system/tasks/*.yml",
   "ai_description": "Packages, hostname, timezone, netplan, unattended-upgrades, iptables firewall (only 22/80/443 + SYN-flood limits), key-only SSH, and a 40-parameter kernel sysctl hardening set (no…",
   "why": "CIS-flavored kernel/network hardening expressed declaratively and re-applied every run."
  },
  {
   "id": "provisioning/container-runtime-04-docker-11-docker-compose",
   "name": "Container runtime (04-docker + 11-docker-compose)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "ansible/roles/04-docker/{templates/daemon.json.j2,tasks/*.yml}",
   "ai_description": "Hardened Docker daemon (journald logging, userland-proxy=false, live-restore=true, custom address pools, capped concurrent pulls), 3 isolated bridge networks (test 172.20/16, prod…",
   "why": "Network-isolated, log-disciplined container host that survives daemon restarts without dropping running apps."
  },
  {
   "id": "provisioning/directory-filesystem-contract-03-directories",
   "name": "Directory & filesystem contract (03-directories)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…nt,secrets,web-roots,logs,monitoring,scripts,nginx,acl-setup,verify}.yml",
   "ai_description": "Builds the full 30+ directory tree (per-env deployment/runtime/logs/backups/secrets), web roots, monitoring dirs, and ACL setup for CI/CD write paths.",
   "why": "Deterministic, verifiable filesystem layout with ACLs — the substrate all other roles build on."
  },
  {
   "id": "provisioning/documentation-corpus-per-role-readmes",
   "name": "Documentation corpus + per-role READMEs",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…ING, GETTING-STARTED, BEFORE-DEPLOYMENT-CHECKLIST, DEPLOYMENT-WORKFLOW*)",
   "ai_description": "~17 markdown guides plus a README per role: deployment guide/workflow, getting-started, quick-reference, troubleshooting, lessons-learned, before-deployment checklist, testing,…",
   "why": "A new hire or acquirer engineer can operate the host from docs alone — runbook maturity = lower bus-factor risk."
  },
  {
   "id": "provisioning/hardening-last-safety-architecture-15-final-hardening-split-danger-playbooks",
   "name": "Hardening-LAST safety architecture (15-final-hardening + split danger-playbooks)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…15-final-hardening/tasks/{main,privilege-reduction,network,firewall}.yml",
   "ai_description": "Connectivity-threatening changes deferred to the last role: privilege reduction -> network -> firewall -> optional SSH.",
   "why": "Senior-grade operational judgment: ship hardening without bricking the box."
  },
  {
   "id": "provisioning/iac-test-harness-molecule-lint-config",
   "name": "IaC test harness (Molecule + lint config)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…ible/molecule/default/{molecule.yml,converge.yml,prepare.yml,verify.yml}",
   "ai_description": "Docker-based Molecule scenario on geerlingguy/docker-ubuntu2404-ansible runs syntax->create->prepare->converge->IDEMPOTENCE->side_effect->verify (infra has CI).",
   "why": "Infrastructure tested in a throwaway container before touching prod, including an idempotence assertion (2nd run = 0…"
  },
  {
   "id": "provisioning/identity-least-privilege-02-users-groups-09-sudoers",
   "name": "Identity & least-privilege (02-users-groups + 09-sudoers)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "ansible/roles/02-users-groups/tasks/*.yml",
   "ai_description": "Deterministic users/groups with exact pinned UIDs/GIDs (e.g. instagram-prod-deploy UID 1006) because docker volume perms depend on them; SSH key deployment;",
   "why": "Least-privilege CI/CD identities + reproducible permission model — the access-control story acquirers diligence."
  },
  {
   "id": "provisioning/observability-provisioning-10-monitoring-loki-grafana-alloy-mtls",
   "name": "Observability provisioning (10-monitoring: Loki + Grafana Alloy + mTLS)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…ring/tasks/{loki-config,alloy-config,loki-compose,mtls-certs,verify}.yml",
   "ai_description": "Provisions the log-aggregation stack: Loki config, Grafana Alloy collector config (NOT Promtail), the Loki docker-compose, and mTLS client-certificate generation for the Loki ingest path.",
   "why": "Centralized logging with mutual-TLS on the ingest channel is enterprise-grade; most startups ship plaintext or none."
  },
  {
   "id": "provisioning/operator-dx-16-zsh-set-up",
   "name": "Operator DX (16-zsh-set-up)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…6-zsh-set-up/{setup-zsh.sh,files/{zshrc,bashrc,fzf.bash},tasks/main.yml}",
   "ai_description": "Installs zsh + Oh-My-Zsh + Powerlevel10k + plugins for the ubuntu operator, explicitly ordered BEFORE ssh-hardening so the operator shell is provisioned while access is still easy.",
   "why": "Small but signals craft — even the operator terminal is provisioned as code."
  },
  {
   "id": "provisioning/orchestration-spine-site-yml-makefile",
   "name": "Orchestration spine (site.yml + Makefile)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "ansible/playbooks/site.yml",
   "ai_description": "site.yml runs all 15 roles in 5 phases (phase3 critical-infra -> phase7 final-hardening); Makefile wraps make deploy/start/verify/full + test/lint/syntax/dry-run/molecule.",
   "why": "One command, full reproducibility of the entire prod host; taggable partial runs."
  },
  {
   "id": "provisioning/secrets-provisioning-05-secrets-honest-vault-gap",
   "name": "Secrets provisioning (05-secrets) + honest Vault gap",
   "domain": "provisioning",
   "status": "STAGED",
   "path": "…les/05-secrets/tasks/{prod-secrets,test-secrets,loki-secrets,verify}.yml",
   "ai_description": "Renders test/prod .env files (0640) and GCP service-account placement, intended to pair with Vault + Google Secret Manager.",
   "why": "Clean separation of secret placement (Ansible) from secret material (GSM at runtime)."
  },
  {
   "id": "provisioning/security-add-ons-14-security",
   "name": "Security add-ons (14-security)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "…e/roles/14-security/tasks/{apparmor,immutable,audit,fail2ban,verify}.yml",
   "ai_description": "AppArmor verification, file-immutability (chattr +i on critical files), security audit, and fail2ban — each step feature-flagged (apply_immutable_flags, configure_fail2ban) for…",
   "why": "Defense-in-depth (MAC profiles + immutable system files + brute-force banning) layered atop kernel/network hardening."
  },
  {
   "id": "provisioning/web-edge-08-nginx",
   "name": "Web edge (08-nginx)",
   "domain": "provisioning",
   "status": "VERIFIED",
   "path": "ansible/roles/08-nginx/tasks/*.yml",
   "ai_description": "Modular nginx reverse proxy: SSL via certbot/Let's Encrypt + mTLS for Loki, site enable/disable, config backup, and an 'nginx -t' test gate before every reload.",
   "why": "Proper TLS edge + reverse-proxy isolation, config-tested before reload — no broken-nginx outages."
  },
  {
   "id": "quality/backend-quality-gate-stack-jacoco-spotbugs-findsecbugs-pmd-owasp-spotless-enforcer",
   "name": "Backend quality-gate stack (JaCoCo, SpotBugs+FindSecBugs, PMD, OWASP, Spotless, Enforcer)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "pom.xml",
   "ai_description": "Six-plugin static-analysis+coverage+governance stack wired into Maven, several fail-the-build: JaCoCo 0.8.11 (3 exec files + merge), SpotBugs 4.8.3.0 + FindSecBugs 1.12.0 (effort=Max,…",
   "why": "Security-first SAST + hard CVE gate + enforced formatting make the codebase audit-ready on day one of diligence;"
  },
  {
   "id": "quality/backend-unit-test-suite-8-236-test",
   "name": "Backend unit-test suite (~8,236 @Test)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "src/test/java/**/*Test.java",
   "ai_description": "~8,236 @Test methods across 241 *Test.java files, run by Surefire in one reused JVM (forkCount=1, reuseForks=true, parallel=classes, threadCount=4) with suite-level embedded Redis;",
   "why": "Unit-test density at this level lets a buyer refactor aggressively post-acquisition with the regression net already…"
  },
  {
   "id": "quality/cucumber-bdd-e2e-suite-15-runners-34-features-175-scenarios",
   "name": "Cucumber BDD E2E suite (15 runners, 34 features, 175 scenarios)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "src/test/resources/**/*.feature",
   "ai_description": "Black-box E2E over HTTP with real Firebase Auth, real Redis sessions, real rate-limiting, GreenMail SMTP.",
   "why": "Acceptance-grade coverage of the exact surfaces a SaaS lives or dies on (auth, sessions, rate-limiting, billing, GDPR)…"
  },
  {
   "id": "quality/fe-greenfield-7-gate-pre-commit-pipeline-check-full",
   "name": "FE greenfield 7-gate pre-commit pipeline (check:full)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "package.json (check:full)",
   "ai_description": "10-step pre-commit gate beyond lint+test: check-no-fuse, check-api-wrappers, check-i18n-parity, check-visual-fixture-coverage, check-visual-baseline-freshness,…",
   "why": "Migration codified: operational proof a live-product rewrite cannot regress visual parity, i18n, or contract fidelity…"
  },
  {
   "id": "quality/graph-assisted-dev-bug-ledger-neo4j-legacybugfix2026-23-bugs-fixed",
   "name": "Graph-assisted-dev bug ledger (Neo4j LegacyBugfix2026, 23 bugs FIXED)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "Neo4j namespace LegacyBugfix2026 (bolt://127.0.0.1:7611)",
   "ai_description": "Live Neo4j ledger of 23 real production-class bugs (all FIXED/FIXED_REVISED/CLOSED_FULLY_MITIGATED) found during the live FE rewrite, each linked to the auth FSM (6 State, 5 AuthStep, 1…",
   "why": "The headline diligence artifact: proves the rewrite found and killed two dozen real bugs before cutover, the team has a…"
  },
  {
   "id": "quality/integration-tier-on-real-postgresql-testcontainers-70-classes",
   "name": "Integration tier on real PostgreSQL (Testcontainers, 70 classes)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "src/test/java/.../integration/ + storage/integration/",
   "ai_description": "70 *IntegrationTest.java classes boot real PostgreSQL via Testcontainers 2.0.3 with full Spring context and Liquibase migrations (H2 deliberately removed). Own JaCoCo exec;",
   "why": "Real-DB integration testing is where most startups cut corners;"
  },
  {
   "id": "quality/live-be-integration-tier-with-api-trace-equivalence-stage-5b",
   "name": "Live-BE integration tier with API trace-equivalence (Stage 5b)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "…ce/ (recorder.ts, canonicalize.ts, diff.ts, expected-drift.ts, types.ts)",
   "ai_description": "Playwright tier boots legacy:4200 + greenfield:4201 + BE:8080, runs the same flow in both frontends, records every request/response pair, canonicalizes (UUID/numeric path -> :id,…",
   "why": "Mathematizes 'the new frontend talks to the backend identically to the old one' - the single biggest cutover risk for a…"
  },
  {
   "id": "quality/visual-parity-ai-screenshot-review-webkit-ios-matrix-5a-5d",
   "name": "Visual-parity + AI screenshot review + WebKit/iOS matrix (5a/5d)",
   "domain": "quality",
   "status": "VERIFIED",
   "path": "…s/visual-parity/ (parity.spec.ts, parity-manifest.ts), e2e-tests/visual/",
   "ai_description": "Pixel-diff-then-AI-triage visual regression: greenfield Material vs legacy Fuse route-by-route at a deliberate 20% threshold (maxDiffPixelRatio default 0.2) across a device matrix incl.",
   "why": "Visual baselines as committed artifacts mean PRs review the image change, not just code (Shopify/Stripe-grade migration…"
  },
  {
   "id": "secrets-crypto/ansible-05-secrets-role-secret-provisioning-0640-vault-encrypted",
   "name": "Ansible 05-secrets role (secret provisioning, 0640, vault-encrypted)",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "ansible/roles/05-secrets/",
   "ai_description": "IaC laying secret material on the host: GCP service-account JSON (decrypted from Ansible Vault) + optional .env templates, with enforced 0640 file / 0750 dir perms,…",
   "why": "Reproducible idempotent secret provisioning with permission enforcement AS A TEST is the bar SOC2 auditors set for…"
  },
  {
   "id": "secrets-crypto/google-cloud-kms-two-key-envelope-kmsvalidationservice",
   "name": "Google Cloud KMS two-key envelope (KMSValidationService)",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "…java/com/sm/instagram/platform/common/security/KMSValidationService.java",
   "ai_description": "Cryptographic core: Spring service wrapping Google Cloud KeyManagementServiceClient with TWO purpose-isolated CryptoKeys in one key ring at europe-central2 (Warsaw, EU residency) -…",
   "why": "Managed-KMS-at-rest with EU data residency and key-per-purpose isolation: rotating/compromising the token key never…"
  },
  {
   "id": "secrets-crypto/google-secret-manager-init-container-secret-load-pipeline",
   "name": "Google Secret Manager init container (secret-load pipeline)",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "…prod/spring-boot-entrypoint.sh + deployment/prod/docker-compose-prod.yml",
   "ai_description": "Sidecar init container: authenticates to GCP with service-account key, lists+fetches all secrets for the env's project, strips PROD_/TEST_ prefix, writes /app/config/secrets.env to a shared…",
   "why": "Startup-in-a-box infra proof: secrets centralized in a managed store, injected at runtime via the cloud-native…"
  },
  {
   "id": "secrets-crypto/hmacutils-constant-time-hmac-sha256-primitive",
   "name": "HmacUtils: constant-time HMAC-SHA256 primitive",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "src/main/java/com/sm/instagram/platform/auth/filter/HmacUtils.java",
   "ai_description": "Shared crypto primitive for all signed-cookie/fingerprint integrity: HmacSHA256 generation + constant-time comparison via MessageDigest.isEqual to defeat timing side-channels.",
   "why": "Timing-attack-resistant comparison is a frequently-missed control;"
  },
  {
   "id": "secrets-crypto/productionsecretservice-dev-prod-secret-resolution-with-offline-fallback",
   "name": "ProductionSecretService: dev->prod secret resolution with offline fallback",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "…main/java/com/sm/instagram/platform/secrets/ProductionSecretService.java",
   "ai_description": "Single Spring abstraction every secret read flows through, auto-selecting strategy by environment.",
   "why": "One swap-point between laptop dev with a .env and prod backed by Google Secret Manager - no code changes between…"
  },
  {
   "id": "secrets-crypto/sha-256-pii-pseudonymization-hashingutil-for-redis-keys-logs",
   "name": "SHA-256 PII pseudonymization (HashingUtil) for Redis keys & logs",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "src/main/java/com/sm/instagram/platform/common/utils/HashingUtil.java",
   "ai_description": "GDPR utility ensuring no raw identifier (Firebase UID, IP, email) ever becomes a Redis key or log token - all SHA-256-hex-hashed first via Apache DigestUtils.",
   "why": "Pseudonymization is a named GDPR Article 32 technique and a data-minimization win: a Redis dump or leaked log exposes…"
  },
  {
   "id": "secrets-crypto/three-independently-rotatable-hmac-secrets-key-separation",
   "name": "Three independently-rotatable HMAC secrets (key separation)",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "…gal/ConsentCookieService.java + auth/service/SessionSecurityService.java",
   "ai_description": "Deliberate separation so each signing concern rotates without cross-contamination: jwt.secret (JWTs), cookie.hmac.secret (session cookies), consent.hmac-secret (legal consent proof cookies,…",
   "why": "Key separation = blast-radius containment + clean rotation runbooks, exactly what auditors look for."
  },
  {
   "id": "secrets-crypto/token-totp-encryption-services-crypto-application-layer",
   "name": "Token & TOTP encryption services (crypto application layer)",
   "domain": "secrets-crypto",
   "status": "VERIFIED",
   "path": "…okenEncryptionService.java + TotpEncryptionService.java + Encrypted.java",
   "ai_description": "Two audit-logged services applying KMS at the persistence boundary. TokenEncryptionService: fail-closed Instagram-token crypto, throws if KMS disabled, emits GDPR: structured audit lines…",
   "why": "Proof encryption is actually USED at the call site, not merely present."
  },
  {
   "id": "subscription/companysubscription-aggregate-root-version-optimistic-lock",
   "name": "CompanySubscription aggregate root (@Version optimistic lock)",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…a/com/sm/instagram/platform/subscription/entity/CompanySubscription.java",
   "ai_description": "1:1-with-user current-state row holding status, previousState (overlay restoration), current/previous/target plan refs, Stripe customer/subscription/schedule IDs, trial fields, and…",
   "why": "A clean DDD aggregate root: one row owns the whole subscription state, with previousState encoding the 'remember where…"
  },
  {
   "id": "subscription/contract-surface-split-controllers-generated-angular-client",
   "name": "Contract surface — split controllers + generated Angular client",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…ays-on) + SubscriptionPaidController.java (@ConditionalOnProperty gated)",
   "ai_description": "BE splits always-on reads (GET /status, /invoices) from payments-gated writes (upgrade/downgrade/trial/portal/consent/config).",
   "why": "Architecture symmetry across the stack is the asset: backend authorization boundaries are reflected in the client's…"
  },
  {
   "id": "subscription/lifecycle-crons-shedlock-protected-daily-processors",
   "name": "Lifecycle crons (ShedLock-protected daily processors)",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…ubscriptionPeriodProcessorCronJob.java + TermsGraceProcessorCronJob.java",
   "ai_description": "Two daily @SchedulerLock(lockAtMostFor=30m) crons. Period processor (4 AM): expired trials, expired downgrades, FREE-period rollover with 24h look-ahead so FREE users never hit a…",
   "why": "Time-driven state transitions done right — distributed-lock-safe in multi-node deploys, payment-toggle-aware, gap-free."
  },
  {
   "id": "subscription/paymentsdisabledbootguard-free-only-kill-switch",
   "name": "PaymentsDisabledBootGuard — free-only kill switch",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…sm/instagram/platform/subscription/config/PaymentsDisabledBootGuard.java",
   "ai_description": "When app.payments.enabled=false, a @PostConstruct guard refuses to boot if any subscription sits in an in-flight PAID status (TRIAL/BUSINESS/ENTERPRISE_ACTIVE, DOWNGRADE_PENDING,…",
   "why": "A literal, reversible kill switch with a fail-fast safety interlock — lets the company ship free-first and enable…"
  },
  {
   "id": "subscription/stripewebhookhandler-3-layer-idempotency-pessimistic-locks",
   "name": "StripeWebhookHandler — 3-layer idempotency + pessimistic locks",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…ubscriptionRepository.java (findBy...ForUpdate, @Lock PESSIMISTIC_WRITE)",
   "ai_description": "Defense-in-depth idempotency: (1) fast-path existsByStripeEventId, (2) DB unique constraint subscription_event_stripe_unique as the real guard catching concurrent-duplicate INSERT…",
   "why": "Webhook idempotency is the #1 way payment integrations corrupt data."
  },
  {
   "id": "subscription/subscriptionevent-immutable-event-sourced-audit-log",
   "name": "SubscriptionEvent immutable event-sourced audit log",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…iption/entity/SubscriptionEvent.java + entity/SubscriptionEventType.java",
   "ai_description": "Append-only subscription_event table written on every transition with eventType (20 types), planFrom/planTo, billing-period window, JSONB metadata, and the unique stripeEventId.",
   "why": "A complete, queryable, auditable financial trail (compliance + dispute resolution + replay-debugging) implemented as…"
  },
  {
   "id": "subscription/subscriptionservice-transition-engine",
   "name": "SubscriptionService transition engine",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…ain/java/com/sm/instagram/platform/subscription/SubscriptionService.java",
   "ai_description": "~940-line engine implementing every transition: trial activation, upgrade (waits for invoice.paid before granting access), downgrade + cancel, five webhook handlers, terms-grace lifecycle,…",
   "why": "This is the engineering, not the coding. Inline comments encode WHY each branch exists (duplicate-webhook avoidance,…"
  },
  {
   "id": "subscription/subscriptionstatus-9-state-enum-contract-anchor",
   "name": "SubscriptionStatus 9-state enum (contract anchor)",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…va/com/sm/instagram/platform/subscription/entity/SubscriptionStatus.java",
   "ai_description": "Canonical 9-value state enum (FREE_ACTIVE, TRIAL_ENTERPRISE, BUSINESS_ACTIVE, ENTERPRISE_ACTIVE, DOWNGRADE_PENDING, PAYMENT_FAILED, TERMS_PENDING, SUSPENDED_LEGAL, ACCOUNT_DEACTIVATED).",
   "why": "Single source of truth with four mechanical enforcement surfaces (Java enum, Postgres CHECK, OpenAPI schema, TS enum)."
  },
  {
   "id": "subscription/terms-pending-grace-overlay-terms-pricing-versioning",
   "name": "TERMS_PENDING grace overlay (terms/pricing versioning)",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…sGraceProcessorCronJob.java + terms_version table (22-03-2026 changelog)",
   "ai_description": "On new terms/pricing, all active subs move to TERMS_PENDING saving previousState, newestTermsAccepted=false, 38-day graceDeadline; users keep previous entitlements during grace.",
   "why": "EU consumer-law compliance (Article 16(m) consent wired into the same flow) implemented as a clean overlay state with…"
  },
  {
   "id": "subscription/test-corpus-307-methods-real-stripe-sandbox-webhook-proofs",
   "name": "Test corpus — 307 methods + real-Stripe-sandbox webhook proofs",
   "domain": "subscription",
   "status": "VERIFIED",
   "path": "…/RunSubscriptionIT.java + features/subscription/subscription-e2e.feature",
   "ai_description": "307 @Test/@ParameterizedTest methods across subscription unit + integration tiers, plus 7 E2E Cucumber scenarios (trial, limits, upgrade, downgrade, payment, invoicing, terms).",
   "why": "Coverage that hits the actual payment provider, not mocks — the evidence base behind 'production bugs caught by tests'."
  }
 ],
 "edges": [
  {
   "from": "network-perimeter/corsproperties",
   "to": "network-perimeter/websecurityconfiguration",
   "type": "CONFIGURES",
   "ai_context": "Typed cors.* properties feed the CorsConfigurationSource bean inside the filter chain"
  },
  {
   "from": "cicd/systemdrollback",
   "to": "cicd/predeploymentbackup",
   "type": "DEPENDS_ON",
   "ai_context": "Restores the snapshot captured before the deployment landed"
  },
  {
   "from": "billing/invoiceretryservice",
   "to": "billing/invoicingport",
   "type": "ORCHESTRATES",
   "ai_context": "Re-submits FAILED invoices through the port until SENT or DEAD_LETTER"
  },
  {
   "from": "billing/stripewebhookhandler",
   "to": "billing/subscriptionservice",
   "type": "ORCHESTRATES",
   "ai_context": "Maps Stripe event types (checkout.session.completed, invoice.paid, subscription.*) to subscription state-machine transitions"
  },
  {
   "from": "cicd/proddeploymentworkflow",
   "to": "cicd/deployandsecure",
   "type": "ORCHESTRATES",
   "ai_context": "Pipeline composes reusable build/backup/deploy-and-secure/reload-validate jobs"
  },
  {
   "from": "legal-consent/legalconsentservice",
   "to": "legal-consent/consentcookieservice",
   "type": "ORCHESTRATES",
   "ai_context": "Issues and reads HMAC-signed consent-proof cookies during consent flows"
  },
  {
   "from": "network-perimeter/nginxansiblerole",
   "to": "network-perimeter/productionsiteconfig",
   "type": "ORCHESTRATES",
   "ai_context": "Deploys nginx.conf, 9 modular confs and 4 site configs from deployment/config/nginx-refactored"
  },
  {
   "from": "cicd/securescriptupload",
   "to": "cicd/validateandexecciscript",
   "type": "PROTECTS",
   "ai_context": "Applies chattr +i immediately after upload, closing the tamper window before execution"
  },
  {
   "from": "cicd/validateandexecciscript",
   "to": "cicd/deployandsecure",
   "type": "PROTECTS",
   "ai_context": "Executes deployment under the chattr +i immutability validation wrapper"
  },
  {
   "from": "legal-consent/hmacutils",
   "to": "legal-consent/consentcookieservice",
   "type": "PROTECTS",
   "ai_context": "HmacSHA256 signing and constant-time comparison primitives make consent cookies forgery-proof"
  },
  {
   "from": "network-perimeter/cloudflarerealipupdate",
   "to": "network-perimeter/nginxratelimiting",
   "type": "PROTECTS",
   "ai_context": "Fresh CF ranges keep $real_ip accurate so per-client limit buckets work behind the edge instead of collapsing onto edge IPs"
  },
  {
   "from": "billing/invoiceretrycronjob",
   "to": "billing/invoiceretryservice",
   "type": "TRIGGERS",
   "ai_context": "Every-15-min ShedLock tick delegates the retry batch"
  },
  {
   "from": "billing/stripewebhookcontroller",
   "to": "billing/stripewebhookhandler",
   "type": "TRIGGERS",
   "ai_context": "Routes signature-verified Stripe events to the handler"
  },
  {
   "from": "billing/subscriptionperiodprocessorcronjob",
   "to": "billing/subscriptionservice",
   "type": "TRIGGERS",
   "ai_context": "Daily 04:00 tick processes expired trials/downgrades plus FREE-plan period rollover"
  },
  {
   "from": "cicd/autorollbackworkflow",
   "to": "cicd/systemdrollback",
   "type": "TRIGGERS",
   "ai_context": "Failed post-deployment validation triggers the systemd-aware restore"
  },
  {
   "from": "legal-consent/consentenforcementcronjob",
   "to": "legal-consent/legalconsentservice",
   "type": "TRIGGERS",
   "ai_context": "Daily 02:00 tick blocks users past the 38-day re-consent grace period"
  },
  {
   "from": "legal-consent/instagramdatadeletionservice",
   "to": "legal-consent/deferreddeletioncronjob",
   "type": "TRIGGERS",
   "ai_context": "Case B queues pending_data_deletion_request rows the daily cron later executes"
  },
  {
   "from": "legal-consent/legalcontroller",
   "to": "legal-consent/legalconsentservice",
   "type": "TRIGGERS",
   "ai_context": "REST consent-capture and status endpoints delegate here"
  },
  {
   "from": "legal-consent/noconsentaccountcleanupcronjob",
   "to": "legal-consent/legalconsentservice",
   "type": "TRIGGERS",
   "ai_context": "Weekly Sunday tick archives zero-consent accounts (GDPR Art. 6 lawful basis)"
  },
  {
   "from": "billing/stripewebhookhandler",
   "to": "billing/subscriptionevent",
   "type": "VALIDATES",
   "ai_context": "Three-layer idempotency: fast-path exists check, subscription_event_stripe_unique DB constraint, optimistic locking on CompanySubscription"
  },
  {
   "from": "cicd/envchecker",
   "to": "cicd/deployandsecure",
   "type": "VALIDATES",
   "ai_context": "Sourced at deploy start; gates execution on required environment variables"
  },
  {
   "from": "cicd/mavenqualitygates",
   "to": "cicd/proddeploymentworkflow",
   "type": "VALIDATES",
   "ai_context": "Build fails on CVSS>=7 dependencies, FindSecBugs findings, PMD violations and coverage shortfall before any artifact can deploy"
  }
 ]
} as const;
