// GENERATED by tools/measure-graph-vs-grep.mjs — what an answer costs with the graph
// against searching and reading the backend source. Re-run to re-measure. Do not edit.

export interface GraphCostQuestion {
  readonly key: string;
  readonly graph: {
    readonly hops: number;
    readonly nodes: number;
    readonly chars: number;
    readonly tokens: number;
    readonly us: number;
  };
  readonly search: {
    readonly terms: readonly string[];
    readonly files: number;
    readonly lines: number;
    readonly bytes: number;
    readonly tokens: number;
    readonly ms: number;
  };
  readonly ratio: number;
}
export interface GraphCostData {
  readonly measuredAt: string;
  readonly backend: { readonly root: string; readonly javaFiles: number; readonly bytes: number };
  readonly questions: readonly GraphCostQuestion[];
}

// prettier-ignore
export const GRAPH_COST: GraphCostData = {
 "measuredAt": "2026-09-24",
 "backend": {
  "root": "checkItOut-be2/src/main/java",
  "javaFiles": 644,
  "bytes": 3808629
 },
 "questions": [
  {
   "key": "dependents",
   "graph": {
    "hops": 1,
    "nodes": 2,
    "chars": 333,
    "tokens": 83,
    "us": 0
   },
   "search": {
    "terms": [
     "SubscriptionService"
    ],
    "files": 16,
    "lines": 22,
    "bytes": 152460,
    "tokens": 38115,
    "ms": 23
   },
   "ratio": 458
  },
  {
   "key": "billing",
   "graph": {
    "hops": 1,
    "nodes": 10,
    "chars": 1771,
    "tokens": 443,
    "us": 1
   },
   "search": {
    "terms": [
     "Stripe",
     "Fakturownia",
     "Invoice"
    ],
    "files": 36,
    "lines": 348,
    "bytes": 249429,
    "tokens": 62357,
    "ms": 21
   },
   "ratio": 141
  },
  {
   "key": "consent",
   "graph": {
    "hops": 1,
    "nodes": 1,
    "chars": 137,
    "tokens": 34,
    "us": 0
   },
   "search": {
    "terms": [
     "ConsentCookie",
     "Hmac"
    ],
    "files": 16,
    "lines": 109,
    "bytes": 429041,
    "tokens": 107260,
    "ms": 20
   },
   "ratio": 3132
  },
  {
   "key": "scheduled",
   "graph": {
    "hops": 1,
    "nodes": 10,
    "chars": 1712,
    "tokens": 428,
    "us": 3
   },
   "search": {
    "terms": [
     "@Scheduled"
    ],
    "files": 20,
    "lines": 23,
    "bytes": 118155,
    "tokens": 29539,
    "ms": 18
   },
   "ratio": 69
  }
 ]
} as const;
